Virtual log
tock/tock pull request #2181
Opened 2020-10-30 06:05 UTC by kevtan

### Pull Request Overview

This pull request implements the virtualization of the log interface, which makes it possible for multiple in-kernel capsules to write persistent logs to flash. It also fixes a minor error in the original `Log::seek` method where the log device would not check to see it was in an idle state before it initiated a seek operation.

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [ ] Ran `make prepush`.

2020-10-30 08:52 UTC, lschuermann commented
Thanks for the contribution. Unfortunately the emojis in the commit messages are not displayed correctly in my tools and break my autocomplete workflow. Would you mind rewording those commits? I'm not sure whether we're at a stage of adoption where this won't break most setups. :confused:

2020-10-30 14:34 UTC, ppannuto commented
@lschuermann I am kinda saddened to hear that there are still tools that break on emoji -- doesn't really bode well for their i18n support.. I quite like the quick visual record the icons provide here. Out of curiosity, what breaks for you?

2020-10-30 15:05 UTC, lschuermann commented
> Out of curiosity, what breaks for you?

Essentially, I see only unicode boxes except one emoji, indicating lacking support in my fonts. One terminal emulator cuts up the emoji as they would be too wide for the otherwise monospace font. In the TTY (which I find myself working in if my GPU is busy serving a VM) I see diamond characters. My script to checkout a commit based on the first characters of a commit message doesn't work (as I can't type emoji). Disclaimer: personal opinion. I don't think that this adds any value, but much rather distracts from the commit message - being a precise description of what was done - and _if_ one can decipher the emoji leading to thinking ["it's just a simple fix for a non critical issue"](https://github.com/carloscuesta/gitmoji/issues/605) or the likes.

2020-10-30 16:16 UTC, bradjc commented
Virtualizing log read is fairly complicated just because there are multiple related calls, and allowing those to be interleaved in any order is probably not what a user of the log read interface expects. Is virtualizing read necessary? Would it be simpler to just virtualize write and assume there will only be one reader?

2020-10-30 16:39 UTC, alistair23 commented
I'm with @lschuermann on the emojis, it's distracting, doesn't really add anything and can easily break tools. Why does one of the commits have a poop in front of it? What does that mean?

It's good to see someone splitting up their commits nicely though :)

2020-10-31 17:11 UTC, kevtan commented
@lschuermann @alistair23 Sorry to hear that the emojis were distracting and breaking tools! I've reworded the commit messages accordingly. I've been following [this](https://gitmoji.carloscuesta.me/) commit message emoji standard in case either of you was curious, but I'll stick with regular ASCII characters for Tock.

2020-10-31 17:12 UTC, kevtan commented
@bradjc Before making a final decision about whether or not read should be virtualized, can we talk about who will actually need to read the log? It's unclear to me what the use case of the log actually is, considering it's not used anywhere in our codebase except for a test harness. It seems reasonable to me that kernel capsules only ever need to write info/error/warning messages and never really need to read them. But who _should_ have read functionality?

2020-11-01 06:57 UTC, phil-levis commented
If there's a log, why shouldn't you be able to virtualize it? You don't have to. But multiple capsules in the kernel might want to be able to read the log, and it would be a problem if you had to choose between them. E.g., you might want ProcessConsole to be able to print the log for you, but also have a network service that lets you request it over TCP/IP.

Virtualizing should be pretty simple: you just need to virtualize the seek pointer. This is what all POSIX file systems do with the open file table; you can open a file multiple times, and each entry in the open file table has its own seek pointer.

2020-11-02 16:35 UTC, alistair23 requested changes

2020-11-02 16:35 UTC, alistair23 commented on capsules/src/log.rs
> +>>>>>>> 7598e876f... 💡 Make "append" documentation render correctly
You have some conflict markers left over.

2020-11-02 16:35 UTC, alistair23 commented on capsules/src/virtual_log.rs
> +        // TODO: Should we check if we're already part of the mux's devices list?
There probably should be a check.

2020-11-02 16:35 UTC, alistair23 commented on capsules/src/virtual_log.rs
> +        self.read_entry_id.set(entry);
I know there is a TODO, but can we return errors?

2020-11-02 16:35 UTC, alistair23 commented on capsules/src/virtual_log.rs
> +    // A pointer to the next virtual log device
These changes should probably be squashed

2020-11-02 16:35 UTC, alistair23 commented on capsules/src/virtual_log.rs
> +        Ok(()))
There are too many brackets here

2020-11-02 16:35 UTC, alistair23 commented on capsules/src/virtual_log.rs
> +    Read(&'static mut [u8], usize),
Does storing the buffer in the state really work?

2020-11-06 19:47 UTC, bradjc commented
Regarding read: the readers that stand out to me are some external tool (like tockloader) that reads the log via reading flash directly (i.e. not involving kernel code at all), or a capsule that wirelessly reports the log. In the first case the kernel does not need to be able to read the log at all, and in the second case there would only be one reader.

I agree virtualizing the read side is entirely possible, but if we merge virtual_log.rs with read virtualization it needs to actually work. One option is to implement it, which would be great. Another option is to only virtualize write and ignore read, which I also think would be fine for many use cases.

2020-11-18 17:30 UTC, bradjc requested changes

2020-11-18 17:30 UTC, bradjc commented on capsules/src/virtual_log.rs
> +        self.read_entry_id.set(entry);
Need to actually use `self.read_entry_id`.

2020-12-04 20:46 UTC, phil-levis commented
Could we clear the changes requested if they should be cleared, then we can look into review for approval?

2020-12-14 20:34 UTC, bradjc commented on capsules/src/virtual_log.rs
> +    }
Need to take care of this TODO?

2020-12-17 15:23 UTC, bradjc commented
I think this is close. There is a TODO in the code that mentions virtualization, and it needs to be switched from draft to full PR.

2021-01-11 22:07 UTC, alevy commented
What's the state of this PR @kevtan?

2021-07-21 18:28 UTC, phil-levis commented
Looks like this won't get wrapped up.

2021-07-21 18:28 UTC, closed without merging