Tock 2.0: update ADC driver to 2.0 API
tock/tock pull request #2312
Opened 2020-12-28 19:26 UTC by alexandruradovici

### Pull Request Overview

This pull request updates the ADC driver to Tock 2.0 API.

### Testing Strategy

I tested the simple ADC using a Microbit v2.
High Speed ADC has not yet been tested.

### TODO or Help Wanted

As I have no board that supports the high speed ADC, @hudson-ayers offered to help and test it.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2020-12-29 15:11 UTC, hudson-ayers requested changes
Thanks so much for taking this one on!

I tested on Imix and got a kernel panic, but if I change a small amount of logic back to how it was before it seems to work correctly. I also have a few other comments

2020-12-29 15:11 UTC, hudson-ayers commented on capsules/src/adc.rs
> +                                    .iter()
also, the new logic leads to an out-of-bounds panic when I run the adc app on Imix, but the old logic seems to work correctly

2020-12-29 16:09 UTC, alexandruradovici commented on capsules/src/adc.rs
> +                                    .iter()
I changed it as it was using chucks which are not available anymore. I will double check it.

2020-12-29 16:10 UTC, alexandruradovici commented on capsules/src/adc.rs
> +            },
Got it

2020-12-29 17:06 UTC, alexandruradovici commented on capsules/src/adc.rs
> +                        calledback = true;
I don't see any other way of doing this.

2020-12-29 17:08 UTC, alexandruradovici commented on capsules/src/adc.rs
> +                                    .iter()
I think I fixed the overflow, let me know if it works.

As a not here, I'm not sure what happens if the user application changes the buffer in between two sample buffers. The `len()` will change and might be lower than the driver expects it to be.

2020-12-29 17:08 UTC, alexandruradovici commented on capsules/src/adc.rs
> +                        // });
Done

2020-12-29 17:11 UTC, alexandruradovici commented on capsules/src/adc.rs
> +            },
It turns out that none of the functions returns `SuccessWithValue`, so I just deleted the match arm.

2020-12-29 17:16 UTC, alexandruradovici commented on capsules/src/adc.rs
> +                    state.app_buf1.len() > 0
It is still strange why it panics when getting the length via the `len()` function. Inside the SharedSlice, it does the same map.

2020-12-29 17:18 UTC, hudson-ayers commented on capsules/src/adc.rs
> +                                    .iter()
why are chunks not available anymore?

2020-12-29 17:39 UTC, alexandruradovici commented on capsules/src/adc.rs
> +                                    .iter()
I might be missing something, `chunks` is implemented for `AppSlice` (https://github.com/tock/tock/blob/195e0061ba1a186dc3a38e388ee2a6d0372dacea/kernel/src/mem.rs#L417), but  not for `ReadWriteAppSlice`.

2020-12-29 17:51 UTC, alexandruradovici commented on capsules/src/adc.rs
> +                                    .iter()
Reverted.

2020-12-29 19:12 UTC, hudson-ayers commented on capsules/src/adc.rs
> +                        calledback = true;
It doesn't look like userspace relied on this, so I think this is okay as-is.

2020-12-29 19:13 UTC, hudson-ayers approved these changes

2020-12-31 00:37 UTC, phil-levis commented
bors r+

2020-12-31 00:48 UTC, merged