usb: Update to use Tock2.0 Driver
tock/tock pull request #2373
Opened 2021-01-20 19:49 UTC by alistair23

### Pull Request Overview

Update the USB Tock2.0 Driver to use the new `Driver` API.

### Testing Strategy

I don't have a way to test this unfortunately. The changes seem very simple so I think it's fine.

### TODO or Help Wanted

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

2021-01-20 21:38 UTC, hudson-ayers requested changes

2021-01-20 21:38 UTC, hudson-ayers commented on kernel/src/callback.rs
> +
I believe this is something we explicitly do not want to provide. See the discussion here: https://github.com/tock/tock/pull/2258#discussion_r542765769

2021-01-20 22:40 UTC, hudson-ayers approved these changes

2021-01-22 04:10 UTC, phil-levis commented
Needs testing.

2021-01-23 05:45 UTC, phil-levis commented
Discussion on the core call today reached consensus that it's OK to merge this untested with the -dev branch, but will need testing before merging -dev into master.

2021-01-23 05:46 UTC, phil-levis commented
bors r+

2021-01-23 05:52 UTC, phil-levis commented
bors r+

2021-01-23 06:09 UTC, merged