arch: cortex-m0: switch to asm!()
tock/tock pull request #2450
Opened 2021-02-22 19:52 UTC by bradjc

### Pull Request Overview

This pull request implements #1923 for cortex-m0.

### Testing Strategy

None? We don't have any cortex-m0 boards.

### TODO or Help Wanted

Help trying to verify my changes are OK.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2021-02-23 18:35 UTC, ppannuto commented on arch/cortex-m0/src/lib.rs
> +    out("r3") _, out("r4") _, out("r5") _, out("r8") _, out("r9") _,
`r7`?

2021-02-23 18:35 UTC, ppannuto commented on arch/cortex-m0/src/lib.rs
> +    out("r2") _, out("r3") _);
I believe this can add the `nomem` and `nostack` options

2021-03-08 16:24 UTC, bradjc commented
Updated. Split hardfault handler to mimic cortex-m version since asm!() macro can be the only thing in a #[naked] function. Also save both r6 and r7 in context switch.

2021-03-08 17:34 UTC, hudson-ayers requested changes

2021-03-08 17:34 UTC, hudson-ayers commented on arch/cortex-m0/src/lib.rs
> +    );
```suggestion
    , options(noreturn)
    );
```
the assembly manually jumps out. Also, naked functions require a single `noreturn` inline asm block -- it is UB for an inline asm block inside a naked function to return.

This suggestion will probably need formatting

2021-03-08 17:34 UTC, hudson-ayers commented on arch/cortex-m0/src/lib.rs
> +    );
```suggestion
    , options(noreturn)
    );
```

2021-03-09 15:06 UTC, ppannuto approved these changes

2021-03-10 18:06 UTC, phil-levis commented
bors r+

2021-03-10 18:17 UTC, merged