add Makefile rules for analyzing stack frames
tock/tock pull request #2488
Opened 2021-03-16 21:40 UTC by hudson-ayers

### Pull Request Overview

This pull request adds 2 Makefile rules for basic stack frame analysis.

Running `make allstack` from the root directory will print out the size of the `reset_handler` stack frame, and the size of the top 5 stack frames, for each Tock board.

Running `make stack-analysis` from a board directory will print the analysis for just that board (which is much faster).

I did not want to include the `-Z emit-stack-sizes` flag in `RUSTC_FLAGS` for default building because it is an unstable flag.

I found this useful when working on #2425 .

### Testing Strategy

This pull request was tested by running the Make rules.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] No updates are required.

### Formatting

- [x] Ran `make prepush`.

2021-03-16 23:09 UTC, lschuermann commented
This looks super awesome and useful. Also great to see how simple the integration is. Do you know what might be causing this issue for me?

```
leons@silicon ~/d/t/t/b/l/arty (ghpr/2488)> make stack-analysis
litex_arty
----------------------
reset_handler stack frame: 
llvm-readelf: Unknown command line argument '--stack-sizes'.  Try: 'llvm-readelf -help'
llvm-readelf: Did you mean '-stackmap'?

5 largest stack frames: 
llvm-readelf: Unknown command line argument '--stack-sizes'.  Try: 'llvm-readelf -help'
llvm-readelf: Did you mean '-stackmap'?
```

I suppose I'm running an ancient version of LLVM somehow (`7.1.0`), need to check where that comes from (@alevy might have the same issue on NixOS). What's a version that works?

2021-03-17 13:58 UTC, alistair23 approved these changes

2021-03-17 15:48 UTC, bradjc requested changes
```
make stack-analysis
hail
----------------------
reset_handler stack frame:
/Users/bradjc/git/tock//tools/stack_analysis.sh: line 9: llvm-readelf: command not found

5 largest stack frames:
/Users/bradjc/git/tock//tools/stack_analysis.sh: line 15: llvm-readelf: command not found
```

2021-03-17 18:13 UTC, hudson-ayers commented
I changed the recipe to use the llvm-tools installed with rustup. Can you try running locally again? `Makefile.common` already installs these tools if they are not present so I think this should work cross-platform.

2021-03-17 18:35 UTC, bradjc approved these changes

2021-03-18 13:55 UTC, alistair23 approved these changes

2021-03-21 23:04 UTC, alevy approved these changes

2021-03-21 23:06 UTC, alevy commented
bors r+

2021-03-21 23:21 UTC, merged