boards: make: check for rustup
tock/tock pull request #2596
Opened 2021-05-24 17:35 UTC by bradjc

### Pull Request Overview

Add a check for rustup to the main board makefile.

I'm setting up a new mac, and this is what happens if you run `make` to build a board:

```
$ make
/Users/bradjc/git/tock/tools/semver.sh: line 32: 10#< > 10#1: syntax error: operand expected (error token is "> 10#1")
/Users/bradjc/git/tock/tools/semver.sh: line 36: 10#< < 10#1: syntax error: operand expected (error token is "< 10#1")
bash: rustup: command not found
bash: rustup: command not found
bash: rustup: command not found
bash: rustup: command not found
bash: rustup: command not found
bash: rustup: command not found
bash: rustc: command not found
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
usage: dirname path
bash: cargo: command not found
make: *** [/Users/bradjc/git/tock/target/thumbv7em-none-eabi/release/hail] Error 127
```

without doing any setup steps. Not clear what the issue is. Now you get:

```
$ make
Error! rustup not found.
Please follow the instructions at https://rustup.rs/ to install rustup.

../Makefile.common:122: *** Rustup required to build Tock..  Stop.
```

### Testing Strategy

Running make before and after installing rustup.

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2021-05-24 18:06 UTC, ppannuto submitted a review, later dismissed

2021-05-24 18:30 UTC, lschuermann requested changes
The Nix build system (`shell.nix`) does not use `rustup` and provides a Rust compiler and targets of the correct version instead. I come to deliberately ignore these errors sometimes. This would completely break the Nix-based workflow.

We might be able to check for the presence of a Rust compiler of the right version instead, prior to the rustup changes? @alevy how would you approach this?

2021-05-24 22:37 UTC, alevy commented
I suggested this on Slack, but what about checking for the _actual_ necessary tools (`rustc` and `cargo`) in the `Makefile` and if they are not present (or have the wrong version) outputting an error message that suggests installing them with rustup (i.e., the same message as @bradjc is currently suggesting)?

This would allow people to get `rustc` / `cargo` however they'd like, including via `nix-shell` and `rustup` and suggest the common case.

2021-05-24 22:40 UTC, bradjc commented
All that is required on the rustup side is having a remotely recent version of rustup installed.

2021-05-24 23:17 UTC, bradjc commented
Thoughts on adding a `NO_RUSTUP` environment variable that prevents the build system from using rustup at all? That would provide a generic way to opt out.

2021-05-25 00:04 UTC, ppannuto commented
Just to see, I implemented a quick version of the `NO_RUSTUP` approach (can always revert this commit if we don't like it). It worked in basic testing, but @alevy, @lschuermann it would be good to verify this actually addresses the issue for nix users.

More generally, I think we have derived a lot of benefit from making the on-boarding process super easy for average users. I know trying to get students spun up on Tock has benefited me immensely here. I think ease of use is one of the tenets we should preserve, but I do agree that it should not be at the expense of making it impossible / much worse for power users.

To that end, I think `NO_RUSTUP` is a good compromise. For nix folks (and others), it's an easy flag to set that turns off all the automated stuff. For the 80%, they still get all the advantages of the automation we've built. If you opt in to this, it means we won't hand hold you, and you have to manage things like rust components yourself, but that feels like something that power users are inclined to be okay with.

2021-05-25 00:06 UTC, alevy commented
`NO_RUSTUP` satisfies my use case (in particular, we will simply add it to the `shell.nix`), so I'm happy with it.

@alistair23 maybe has a dissenting idea why this is undesirable?

2021-05-25 00:10 UTC, alistair23 commented
It's not just nix that doesn't use rustup. Fedora doesn't, which I assume also means RHEL and CentOS (and what it turned into) doesn't. That's a reasonable number of Linux users there.

I think it would be better to check for `rustc` and `cargo`

2021-05-25 00:21 UTC, ppannuto commented
That's distressing -- I was under the impression that rustup sought to cover major distributions. I'm not surprised they wouldn't do something like gentoo, but missing Fedora is a red flag.

Quick googling (as I haven't been a fedora user in a few years...) finds this: https://developer.fedoraproject.org/tech/languages/rust/further-reading.html, which seems to imply that installing rustup is reasonably well supported on Fedora?

2021-05-25 01:31 UTC, alistair23 commented
Yeah, rustup can be installed and seems to work well. I think lots of users would just `dnf install rustc cargo` (as described here: https://developer.fedoraproject.org/tech/languages/rust/rust-installation.html) and then we are going to throw an error saying that they haven't installed Rust.

What is wrong with checking for `rustc` and `cargo` instead of `rustup`?

2021-05-25 03:09 UTC, ppannuto commented
We need rustup to support this part:

```make
# Verify that various required Rust components are installed. All of these steps
# only have to be done once per Rust version, but will take some time when
# compiling for the first time.
LLVM_TOOLS_INSTALLED := $(shell $(RUSTUP) component list | grep 'llvm-tools-preview.*(installed)' > /dev/null; echo $$?)
ifeq ($(LLVM_TOOLS_INSTALLED),1)
  $(shell $(RUSTUP) component add llvm-tools-preview)
endif
ifneq ($(shell $(RUSTUP) component list | grep rust-src),rust-src (installed))
  $(shell $(RUSTUP) component add rust-src)
endif
ifneq ($(shell $(RUSTUP) target list | grep "$(TARGET) (installed)"),$(TARGET) (installed))
  $(shell $(RUSTUP) target add $(TARGET))
endif
```

Installing components a pretty arcane corner of the rust ecosystem for a new user.

2021-05-25 03:33 UTC, alistair23 commented
Yeah, auto adding the target is really useful. I guess the `NO_RUSTUP` will have to do then.

2021-05-25 08:01 UTC, lschuermann approved these changes
I'm fine with adding `NO_RUSTUP` as a way to suppress this check. I added two commits, to set the variable in the Nix environment, as well as to inform users about the ability to provide all required tools and resources on their own and set `NO_RUSTUP` accordingly. The Nix environment works without warnings now.

I think it's both important that new users can be onboarded quickly (for which `rustup` arguably does a pretty good job), but also that we don't rely on or enforce using this single tool to provision the toolchain required. While good for development, `rustup` is probably a rather bad fit for automatic and/or reproducible builds, or for auditing the dependencies required to build Tock. Not requiring `rustup`, at least to build boards, prevents us from having a "vendor lock-in" here.

2021-05-25 14:15 UTC, bradjc commented
All rustup does is setup the toolchain specified in the `rust-toolchain` file (which is why the makefile checks for at least version 1.11, where that feature was added). So as long as Rust versions their compiler correctly, there shouldn't be any issue with reproducible builds on rustup's account. Cargo manages dependencies, so I'm not sure why using rustup or not would have any affect on dependency tracking. Rustup is an official Rust project, so there is no more vendor lock in than using cargo or rustc.

The automatic downloads I guess could be a problem, but that's what cargo does as well.

2021-05-25 15:27 UTC, ppannuto commented on boards/Makefile.common
> +RUSTUP    ?= true
The thinking here was to replace invocations of `rustup` with no-ops (the very helpful `true` program). That way, any future uses of `RUSTUP` anywhere in the build system don't need to remember to add `NO_RUSTUP` feature gates around the invocation. I was particularly imagining the case where a board might invoke rustup in some support role.

The secondary benefit is that the `make V=1` would then show that someone has opted out of using rustup.

I'm not married to this approach, but I think it has benefits.

2021-05-25 15:35 UTC, bradjc commented on boards/Makefile.common
> +endif # $(NO_RUSTUP) ?
But why not? It's confusing that we use rustup a little when NO_RUSTUP is set.

2021-05-25 16:37 UTC, ppannuto commented on boards/Makefile.common
> +endif # $(NO_RUSTUP) ?
Yeah, I don't have a great answer for that. I guess I wanted to prove that the `true` idea worked, but that shouldn't be the long-term position for this block. Moved it.

2021-05-25 18:08 UTC, bradjc commented on boards/Makefile.common
> +RUSTUP    ?= true
Yeah OK I didn't see that we also print the rustup version.

2021-05-25 22:22 UTC, alistair23 approved these changes

2021-06-02 20:10 UTC, alevy approved these changes

2021-06-03 07:03 UTC, lschuermann approved these changes

2021-06-03 18:11 UTC, lschuermann commented
bors r+

2021-06-03 18:25 UTC, merged