Add core WG notes for 2021-05-28
tock/tock pull request #2604
Opened 2021-06-01 20:00 UTC by alevy

[Rendered](https://github.com/tock/tock/blob/corenotes/2021-05-28/doc/wg/core/notes/core-notes-2021-05-28.md)

2021-06-01 20:14 UTC, hudson-ayers approved these changes

2021-06-01 20:14 UTC, hudson-ayers commented on doc/wg/core/notes/core-notes-2021-05-28.md
> +Phil: experience is dumps for panic has all the information necessary but hard to find
```suggestion

Phil: experience is dumps for panic has all the information necessary but hard to find
```

2021-06-01 21:05 UTC, brghena requested changes

2021-06-01 21:05 UTC, brghena commented on doc/wg/core/notes/core-notes-2021-05-28.md
> +Branden: Please share slide deck? Video?
```suggestion
Branden: Please share slide deck? Video? [Slides are located here](https://docs.google.com/presentation/d/1rWZU8UPYhbEYJ44ri1KKlzCbSIzo_eYPDP9AnRPs0DY/edit?usp=sharing)
```

2021-06-01 23:19 UTC, jrvanwhy submitted a review, later dismissed

2021-06-02 04:04 UTC, brghena approved these changes

2021-06-02 05:25 UTC, hudson-ayers approved these changes

2021-06-02 18:19 UTC, alevy commented
bors r+

2021-06-02 18:31 UTC, merged