rp2040: SysInfo peripheral
tock/tock pull request #2645
Opened 2021-07-01 12:33 UTC by irina-b-dev

### Pull Request Overview

This pull request adds the support for the SysInfo peripheral of RP2040

### Testing Strategy

This pull request was tested using raspberry pi pico. 

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2021-07-01 14:15 UTC, bradjc submitted a review, later dismissed

2021-07-01 15:14 UTC, ppannuto approved these changes

2021-07-01 21:14 UTC, hudson-ayers approved these changes

2021-07-01 21:15 UTC, hudson-ayers requested changes

2021-07-01 21:15 UTC, hudson-ayers commented on chips/rp2040/src/sysinfo.rs
> +        (0x440 => @END),
```suggestion
        (0x044 => @END),
```

2021-07-02 15:10 UTC, bradjc approved these changes

2021-07-02 20:06 UTC, hudson-ayers approved these changes
bors r+

2021-07-02 20:23 UTC, merged