Added troubleshooting for microbit v2 if openOCD could not find MEM-AP
tock/tock pull request #2675
Opened 2021-07-20 12:20 UTC by irina-b-dev

### Pull Request Overview

This pull request adds troubleshooting section to the microbit v2 readme. Some of the microbits have a debugging protection active that prevents openOCD from controlling the chip.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2021-07-20 17:50 UTC, brghena requested changes
Thanks for this! Always good to have more troubleshooting information. A few small fixes, but otherwise looks good.

2021-07-20 17:50 UTC, brghena commented on boards/microbit_v2/README.md
> +> Another solution would be to use Nordic's [nrfjprog](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.tools/dita/tools/nrf5x_command_line_tools/nrf5x_command_line_tools_lpage.html) to
```suggestion
> Another solution would be to use Nordic's [nrfjprog](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.tools/dita/tools/nrf5x_command_line_tools/nrf5x_command_line_tools_lpage.html) to unlock your chip via `$ nrfjprog -f NRF52 --recover`, but this requires the use of a JLink debugger (on-board nRF52 DKs or external).
```

2021-07-20 17:50 UTC, brghena commented on boards/microbit_v2/README.md
> +> Another solution would be to use Nordic's [nrfjprog](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.tools/dita/tools/nrf5x_command_line_tools/nrf5x_command_line_tools_lpage.html) to
The nrfjprog link is also bad. Maybe you meant this: https://infocenter.nordicsemi.com/index.jsp?topic=%2Fug_nrf_cltools%2FUG%2Fcltools%2Fnrf_nrfjprogexe.html

2021-07-20 17:50 UTC, brghena commented on boards/microbit_v2/README.md
> +OpenOCD displays `Could not find MEM-AP to control the core` error when trying to connect to Micro:Bit. This means that the Micro:boit has [control access port](https://infocenter.nordicsemi.com/topi
```suggestion
OpenOCD displays `Could not find MEM-AP to control the core` error when trying to connect to Micro:bit. This means that the Micro:bit has [control access port](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.nrf52832.ps.v1.1/dif.html?cp=2_2_0_15_1#concept_udr_mns_1s) protection enabled. 
```

2021-07-20 17:51 UTC, brghena commented
I'm surprised that some Micro:bits are coming with debugging protection active. Do you have any insight into how common this is or under what situations someone might run into it?

2021-07-21 18:54 UTC, irina-b-dev commented
@brghena Thank you for your feedback! I don't know how common it is for Micro:bits to have debugging protection active.
I did try to use openOCD with two other Micro:bits and they didn't have it enabled.
I might have enabled it by mistake when I used a nightly version of openOCD (I encountered this error afterwards, when using the stable version of openOCD v0.10.0).

2021-07-21 19:43 UTC, brghena requested changes

2021-07-21 19:43 UTC, brghena commented on boards/microbit_v2/README.md
> +> Another solution would be to use Nordic's [nrfjprog](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.tools/dita/tools/nrf5x_command_line_tools/nrf5x_command_line_tools_lpage.html) to
The link here is still broken. https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.tools/dita/tools/nrf5x_command_line_tools/nrf5x_command_line_tools_lpage.html resolves into a "Page Not Found" for me.

2021-07-29 13:35 UTC, bradjc commented on boards/microbit_v2/README.md
> +> Another solution would be to use Nordic's [nrfjprog](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.tools/dita/tools/nrf5x_command_line_tools/nrf5x_command_line_tools_lpage.html) to
```suggestion
> Another solution would be to use Nordic's [nrfjprog](https://www.nordicsemi.com/Products/Development-tools/nRF-Command-Line-Tools) to unlock your chip via `$ nrfjprog -f NRF52 --recover`, but this requires the use of a JLink debugger (on-board nRF52 DKs or external).
```

2021-07-29 13:36 UTC, merged