Core working group notes of 2021-07-16
tock/tock pull request #2691
Opened 2021-07-25 17:05 UTC by lschuermann

### Pull Request Overview

Add core team call notes of 2021-07-16 As always, I hope to have attributed each argument correctly and not misrepresented anyone's opinion.

### Testing Strategy

This pull request was tested by reading with spellcheck on.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [N/A] Ran `make prepush`.

2021-07-25 17:34 UTC, brghena submitted a review, later dismissed

2021-07-25 17:51 UTC, alexandruradovici requested changes

2021-07-25 17:51 UTC, alexandruradovici commented on doc/wg/core/notes/core-notes-2021-07-16.md
> +* Alex: Okay, that makes and could simply things. Then a second header
```suggestion
* Alex: Okay, that makes things simpler. Then a second header parameter
```

2021-07-25 17:51 UTC, alexandruradovici commented on doc/wg/core/notes/core-notes-2021-07-16.md
> +* Alexandru: The length of the data. TLV header plus the data.
```suggestion
* Alexandru: It describes the length of the header (TLV header plus the data).
```

2021-07-25 19:48 UTC, alexandruradovici approved these changes

2021-07-26 14:11 UTC, hudson-ayers approved these changes

2021-07-26 15:55 UTC, brghena commented
bors r+

2021-07-26 16:08 UTC, merged