Updated lps25hb to handle i2c errors
tock/tock pull request #2698
Opened 2021-07-27 09:36 UTC by Cristiana959

### Pull Request Overview

This pull request adds i2c error verification for the lps25hb drivers.

### Testing Strategy

This pull request was not tested as I do not own the sensor.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x]  No updates required.

### Formatting

- [x] Ran `make prepush`.

2021-07-27 19:59 UTC, bradjc requested changes

2021-07-27 19:59 UTC, bradjc commented on capsules/src/lps25hb.rs
> +        if _status != Ok(()) {
```suggestion
    fn command_complete(&self, buffer: &'static mut [u8], status: Result<(), i2c::Error>) {
        if status != Ok(()) {
```

2021-07-27 19:59 UTC, bradjc commented on capsules/src/lps25hb.rs
> +                                    kernel::into_statuscode(Err(error.into())),
The first argument is the index of the upcall. Since there is only one upcall, this should always be 0.

2021-07-28 15:25 UTC, bradjc approved these changes

2021-07-28 18:22 UTC, lschuermann approved these changes

2021-07-28 19:27 UTC, bradjc commented
Need to update to `kernel::errorcode::into_statuscode`.

2021-07-29 00:31 UTC, alistair23 approved these changes

2021-07-29 13:06 UTC, bradjc approved these changes

2021-07-29 13:06 UTC, bradjc commented
bors r+

2021-07-29 13:18 UTC, merged