kernel: process: Split panic debug functions to their own trait
tock/tock pull request #2772
Opened 2021-08-13 21:25 UTC by bradjc

### Pull Request Overview

Split process print functions into their own trait so that Rust will elide them if the trait is never used.

I spent 6 minutes on this as a rough proof of concept. Was going alright until:

```
$ make
   Compiling kernel v0.1.0 (/Users/bradjc/git/tock/kernel)
   Compiling cortexm v0.1.0 (/Users/bradjc/git/tock/arch/cortex-m)
   Compiling capsules v0.1.0 (/Users/bradjc/git/tock/capsules)
   Compiling cortexm4 v0.1.0 (/Users/bradjc/git/tock/arch/cortex-m4)
   Compiling sam4l v0.1.0 (/Users/bradjc/git/tock/chips/sam4l)
   Compiling components v0.1.0 (/Users/bradjc/git/tock/boards/components)
   Compiling hail v0.1.0 (/Users/bradjc/git/tock/boards/hail)
error[E0308]: mismatched types
  --> boards/hail/src/io.rs:73:9
   |
73 |         &PROCESSES,
   |         ^^^^^^^^^^ expected slice, found array of 20 elements
   |
   = note: expected reference `&'static [Option<&'static (dyn ProcessDebug + 'static)>]`
              found reference `&[Option<&'static (dyn Process + 'static)>; 20]`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `hail`
```

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [ ] Ran `make prepush`.

2021-08-16 02:34 UTC, alistair23 approved these changes
I like the concept! This is related to https://github.com/tock/tock/issues/2594

2021-08-17 15:22 UTC, bradjc commented
As I learn more about this, I'm starting to think this approach won't work, and `Process` will have all of the functions just like before. https://stackoverflow.com/questions/49543778/why-cant-i-cast-a-box-with-an-extended-trait-to-a-box-with-the-base-trait

2021-08-17 15:49 UTC, hudson-ayers commented
Yeah, I agree this will not work as written. In order for this approach to work, there would need to be some `ProcessStandardNoDebug` struct which would duplicate the `Process` trait implementation but have empty stubs for the `ProcessDebug` trait. But then we are back to duplicating code, and this is not really much better than without the new trait.

We could use macros to prevent code duplication, but having large code blocks in macros sucks, since rustfmt and rust-analyzer do not work as well in the body of macros, and error messages for code inside macros are much harder to parse.

I think the last option would be to have a generic type parameter on `ProcessStandard` that indicates whether to include debug info. Then you could do something like

```rust
struct ProcessStandard<const DEBUG: bool>{//...}

impl ProcessDebug for ProcessStandard<true> {
    // actually implement the trait
}

impl ProcessDebug for ProcessStandard<false> {
    // empty stubs for all methods
}
```

That said, I am not sure how easy it would actually be to make a change like this until I have a chance to try it.

2021-08-17 15:54 UTC, bradjc commented
> ```rust
> struct ProcessStandard<const DEBUG: bool>{//...}
> 
> impl ProcessDebug for ProcessStandard<true> {
>     // actually implement the trait
> }
> 
> impl ProcessDebug for ProcessStandard<false> {
>     // empty stubs for all methods
> }
> ```

Makes sense, but this doesn't really give us the API we want, and we would be back to the problem where you would need to make (at least) two changes: to the `PROCESSES` array in main.rs and to the panic handler in io.rs, and, they wouldn't be mutually enforced (you could remove the panic debug call in io.rs but not remove the process printing code).

It seems like we would actually be better off creating a new `ProcessPrinter` trait, and creating a new object that displays a process.

2021-08-17 16:09 UTC, hudson-ayers commented
> > ```rust
> > struct ProcessStandard<const DEBUG: bool>{//...}
> > 
> > impl ProcessDebug for ProcessStandard<true> {
> >     // actually implement the trait
> > }
> > 
> > impl ProcessDebug for ProcessStandard<false> {
> >     // empty stubs for all methods
> > }
> > ```
> 
> Makes sense, but this doesn't really give us the API we want, and we would be back to the problem where you would need to make (at least) two changes: to the `PROCESSES` array in main.rs and to the panic handler in io.rs, and, they wouldn't be mutually enforced (you could remove the panic debug call in io.rs but not remove the process printing code).
> 
> It seems like we would actually be better off creating a new `ProcessPrinter` trait, and creating a new object that displays a process.

Having a separate object for displaying a process requires giving that object the ability to inspect a process, which probably means keeping many of the existing debug_whatever functions on the Process trait, right? Unless we change the visibility of every field to be `pub(crate)`, which I also do not think we want to do.

2021-08-17 16:19 UTC, bradjc commented
> Having a separate object for displaying a process requires giving that object the ability to inspect a process, which probably means keeping many of the existing debug_whatever functions on the Process trait, right?

Yes. Were those ever going away?

2021-08-17 16:50 UTC, hudson-ayers commented
I was hoping to re-open a revised version of https://github.com/tock/tock/pull/1830 after this PR

2021-08-17 17:20 UTC, bradjc commented
> I was hoping to re-open a revised version of #1830 after this PR

Wait so #2759 is giving the proverbial mouse a cookie? We need to brainstorm solutions to solve whatever the entire problem is.

2021-08-17 18:44 UTC, hudson-ayers commented
> > I was hoping to re-open a revised version of #1830 after this PR
> 
> Wait so #2759 is giving the proverbial mouse a cookie? We need to brainstorm solutions to solve whatever the entire problem is.

I mentioned it on the core call, I just haven't had a chance to update #1830 to the 2.0 process code yet. It sounds like we do still need to brainstorm solutions for the larger problem though, and I didn't want to take the time to update #1830 until we reach consensus on how we want to do this.

2021-08-17 21:42 UTC, phil-levis requested changes
Let's not do piecemeal tweaks on the Process trait. Let's actually redesign it. Engineering, not crafting.

2021-08-18 04:44 UTC, alistair23 commented
I thought with this trait split we could then do something like:

```rust
#[cfg(debug_prints)]
impl<C: Chip> ProcessDebug for ProcessStandard<'_, C> {
    fn print_memory_map(&self, writer: &mut dyn Write) {
        // Full implementation
    }
}

#[cfg(not(debug_prints))]
impl<C: Chip> ProcessDebug for ProcessStandard<'_, C> {
    fn print_memory_map(&self, writer: &mut dyn Write) {
        // Don't do anything
    }
}
```

The idea here is then it's up to boards to use/not use the debug_prints feature. It seems like a useful board feature (based on flash contraints).

The problem with https://github.com/tock/tock/pull/2759 is it has to impact all boards or no board gets the size benefit by default.

2021-09-08 18:53 UTC, hudson-ayers commented
> I thought with this trait split we could then do something like:
> 
> ```rust
> #[cfg(debug_prints)]
> impl<C: Chip> ProcessDebug for ProcessStandard<'_, C> {
>     fn print_memory_map(&self, writer: &mut dyn Write) {
>         // Full implementation
>     }
> }
> 
> #[cfg(not(debug_prints))]
> impl<C: Chip> ProcessDebug for ProcessStandard<'_, C> {
>     fn print_memory_map(&self, writer: &mut dyn Write) {
>         // Don't do anything
>     }
> }
> ```
> 
> The idea here is then it's up to boards to use/not use the debug_prints feature. It seems like a useful board feature (based on flash contraints).
> 
> The problem with #2759 is it has to impact all boards or no board gets the size benefit by default.

If we are willing to use `cfg`, you can get the same benefit with the #2759 approach without the added complexity of splitting the traits by just using:

```rust
/// A unique instance of `Config` where compile-time configuration options are defined. These
/// options are available in the kernel crate to be used for relevant configuration.
pub(crate) const CONFIG: Config = Config {
    #[cfg(not(trace_syscalls))]
    trace_syscalls: false,
    #[cfg(trace_syscalls)]
    trace_syscalls: true,
    #[cfg(not(debug_load_processes))]
    debug_load_processes: false,
    #[cfg(debug_load_processes)]
    debug_load_processes: true,
    #[cfg(not(debug_processes))]
    debug_processes: false,
    #[cfg(debug_processes)]
    debug_processes: true,
}
```

2021-09-23 14:45 UTC, bradjc commented
Closing this as it isn't going to work.

2021-09-23 14:45 UTC, closed without merging