[imxrt1050-evkb] Fix GPIO interrupts
tock/tock pull request #2786
Opened 2021-08-17 11:08 UTC by valexandru

### Pull Request Overview

This pull request fixes gpio interrupts on the i.MX RT 1052 EVKB.

While I was testing the buttons example on the i.MX RT 1052 EVKB, I discovered that the interrupts are not enabled by default. However, if I set up a delay of 1000 ms so that a different interrupt is triggered before the gpio one, the gpio interrupts will work. Therefore, in order to prevent this, we have to specifically enable the interrupt in the nvic. 

This seems to be a bug in the i.MX RT 1052 EVKB board and requires to manually enable the interrupts in the nvic.

### Testing Strategy

This pull request was tested using an iMXRT1052 EVKB board.

### TODO or Help Wanted

This pull request needs feedback.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2021-08-17 14:30 UTC, hudson-ayers submitted a review, later dismissed

2021-08-17 15:11 UTC, bradjc requested changes
This seems bad. Why are the nvic interrupts not all enabled by default? Particularly why does the chip init look like:

https://github.com/tock/tock/blob/3c9468e522b8f67aca0ef91045e25a19fbb2fffb/chips/imxrt10xx/src/lib.rs#L228-L235

which does not enable all interrupts? Compare to the sam4l chip init:

https://github.com/tock/tock/blob/3c9468e522b8f67aca0ef91045e25a19fbb2fffb/chips/sam4l/src/lib.rs#L81-L85

Tock assumes all interrupts are enabled at the interrupt controller level, and relies on individual peripherals to disable interrupts on a per-peripheral basis. That avoids all issues like this. Did we need to special case this chip for some reason?

2021-08-19 19:46 UTC, alexandruradovici commented
I reversed the changes and enabled all interrupts. Please @valexandru  test the pio interrupt.

2021-08-19 21:48 UTC, valexandru commented
Yes, it works now, after enabling the interrupts in lib.rs. Thank you @alexandruradovici for making the changes while I was away.

2021-08-19 22:03 UTC, hudson-ayers approved these changes
bors r+

2021-08-19 22:30 UTC, hudson-ayers commented
bors r+

2021-08-19 22:41 UTC, merged