rfc: add low level driver capability
tock/tock pull request #2800
Opened 2021-08-27 07:38 UTC by alexandruradovici

### Pull Request Overview

This pull request adds the `LowLevelDriverCreationCapability`. While talking a look at Tock's source together with an industry partner, we realized that there is nothing much stopping a capsule from creating a certain peripheral and using it directly. Capsules would not be able to use interrupts, as they would not be registered with the kernel's infrastructure, but could use any synchronous interfaces.

So far I have modified the Raspberry Pi Pico just as a proof of concept.

### Testing Strategy

N/A

### TODO or Help Wanted

This pull request still needs feedback.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2021-08-29 23:56 UTC, hudson-ayers commented
Is there a specific example of where creating two instances of a peripheral would be unsound (as opposed to just leading to unexpected behavior from the peripheral)?

In general it seems that the issue with something like a DMA peripheral would be that calling set on a register is safe even if modifying that register leads to changing arbitrary memory based on the values of other registers. In which case the fix there would be modifying the Tock-registers library to support marking certain register operations as unsafe when declaring a registers struct

2021-08-31 16:32 UTC, lschuermann commented
> In general it seems that the issue with something like a DMA peripheral would be that calling set on a register is safe even if modifying that register leads to changing arbitrary memory based on the values of other registers.

Yes. We start getting into dangerous territory in the Rust memory-safety sense as soon as we're controlling hardware which can mutate memory outside of the peripheral's memory-mapped address space. For any such peripheral I would assume that arbitrarily bad things happen once we have two drivers which think they have exclusive control over said peripheral. We can't reasonably assume any correct behavior whatsoever beyond this point.

> In which case the fix there would be modifying the Tock-registers library to support marking certain register operations as unsafe when declaring a registers struct.

I disagree. This goes in the exact same direction as #2593. At the end of that extensive discussion it seems to make the most sense to stick with the  "unsafe creation, safe use" paradigm. We explicitly put the burden on the user, when creating the `tock-registers` type (e.g. through `StaticRef::new`), to ensure that Rusts memory safety requirements will not be violated.

It also wouldn't make much sense semantically: from `tock-registers`' point of view, if we're talking about valid accesses to writable registers of DMA peripherals, the accesses themselves are entirely sound operations, no damage done here. The consequences stem from the "bigger picture", where the particular sequence of register access might lead to unsoundness. This is best gated through an `unsafe` on the high-level instance managing this sequence of accesses, i.e. the driver.

2021-08-31 16:38 UTC, hudson-ayers commented
The reason we publicly export the `StaticRef` in places where the constructor takes in a `StaticRef` is so that you can create peripherals from a board crate if you do not want to use the default set of peripherals for a given chip. You cannot mark a `const` as `unsafe` to use, unfortunately.

We could mark all of the peripheral constructors as `unsafe`, which I would consider preferable to using a capability. However in many cases I think that having multiple instances of a peripheral would not necessarily lead to memory unsafety -- it is more specific to certain peripherals which let you do DMA-like stuff.

2021-08-31 17:48 UTC, lschuermann commented
> The reason we publicly export the `StaticRef` in places where the constructor takes in a `StaticRef` is so that you can create peripherals from a board crate if you do not want to use the default set of peripherals for a given chip. You cannot mark a `const` as `unsafe` to use, unfortunately.

Can't we just simply, instead of exporting the constructed `StaticRef`, export a typed pointer to this struct? This way we still have some degree of type safety and annotation (which of course in the case of a pointer can be easily overriden through casting) but would delay the unsafety to the construction of the `StaticRef` either in the default peripherals struct (creating this would need to become unsafe then) or the custom periperhals struct in the board file.

2021-09-02 12:59 UTC, hudson-ayers commented
> Can't we just simply, instead of exporting the constructed `StaticRef`, export a typed pointer to this struct? This way we still have some degree of type safety and annotation (which of course in the case of a pointer can be easily overriden through casting) but would delay the unsafety to the construction of the `StaticRef` either in the default peripherals struct (creating this would need to become unsafe then) or the custom periperhals struct in the board file.

Yes, I think that would work fine.

2021-09-23 14:53 UTC, bradjc requested changes
I don't think this is an appropriate use of capabilities. Any crate that can create chip drivers (scientifically the chip itself and boards) can also call unsafe and create its own capability at will. That eliminates the benefit of capabilities (i.e. that they are enforced by the compiler).

2021-11-16 19:30 UTC, closed without merging