Add link to a Tock book
tock/tock pull request #2934
Opened 2022-01-06 12:13 UTC by alexandruradovici

### Pull Request Overview

The [Getting Started with Secure Embedded Systems](https://link.springer.com/book/10.1007/978-1-4842-7789-8) about using Tock with the micro:bit and Raspberry Pi Pico boards has been published. A big thank you to @brghena and @lschuermann for their reviews, their feedback has been very useful for us.

This pull request adds a link to the book in the main `readme` and the two board's `readme`s.

I know that it is not a free book, but I do think it might bring a lot of value to people that want to get started.

### Testing Strategy

N/A

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2022-01-17 05:50 UTC, phil-levis commented on boards/microbit_v2/README.md
> +For furher details and exmaples about how to use Tock with the BBC micro:bit, you might
Typos

2022-01-17 05:51 UTC, phil-levis commented on boards/raspberry_pi_pico/README.md
> +For furher details and exmaples about how to use Tock with the Raspberry Pi Pico, you might
Typos

2022-01-17 05:51 UTC, phil-levis requested changes
Just fix a few typos, then happy to approve.

2022-01-17 09:56 UTC, alexandruradovici commented
> Just fix a few typos, then happy to approve.

Fixed them, thank you for pointing them out.

2022-01-17 19:07 UTC, hudson-ayers approved these changes

2022-01-20 02:34 UTC, brghena approved these changes

2022-01-20 02:34 UTC, brghena commented
bors r+

2022-01-20 02:57 UTC, brghena commented
Oops. Phil still had requested changes. I'll leave it for him to merge.

Thanks for noticing bors!

2022-01-31 14:59 UTC, alexandruradovici commented
I think this is good to go as I think I addressed all Phil's concerns.

2022-01-31 18:27 UTC, hudson-ayers commented
bors r+

2022-01-31 19:23 UTC, merged