boards/opentitan: Update the README
tock/tock pull request #3062
Opened 2022-06-22 23:56 UTC by alistair23

### Pull Request Overview

Update the README to fix some outdated information and point users to
use our commit and steps.

### Testing Strategy

### TODO or Help Wanted

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

2022-06-23 00:45 UTC, phil-levis requested changes
Please link to the OpenTitan documentation for the specific commit, not the most up to date documentation. Otherwise the OpenTitan documentation is incorrect. 

I recommend that you go through the instructions in a clean VM exactly as they're written to make sure they work as is.

2022-06-23 01:12 UTC, phil-levis commented on boards/opentitan/README.md
> +./meson_init.sh
Yes -- this was the source of about half of my confusion; these instructions are for the specific prior commit, but it links to the OT documentation for the current commit, which uses Bazel.

2022-06-23 02:15 UTC, alistair23 commented on boards/opentitan/README.md
> +./meson_init.sh
Yep, already on it: https://github.com/tock/tock/pull/3056

The problem is there are ePMP issues with the newer versions so this is a stop gap until we can update

2022-06-23 05:54 UTC, phil-levis requested changes

2022-06-23 05:54 UTC, phil-levis commented on boards/opentitan/README.md
> +In general the OpenTitan project has
Please cut this link -- better to just point people at what the right thing to do is than say "Here's the documentation, actually that's the wrong documentation instead look at this other documentation."

2022-06-23 17:05 UTC, hudson-ayers commented
I tried to follow these instructions for the newer commit that we are trying to upgrade OT to, and ran into two issues:

1. `$ ci/scripts/build-chip-verilator.sh earlgrey` hangs with no output after running the fusesoc command (I waited for ~40 minutes, is there a chance I could go that long with no output?)
2. `ninja -C build-out all` fails for a bunch of targets, citing missing files in the OT repository -- maybe I missed a submodule I was supposed to fetch or something?. Rerunning with `ninja -k 0 -C build-out all` gets further and builds some targets, but still seems to fail for some of the targets we need.

This may not be the right place for these complaints, just wanted to note that I tried to follow these instructions and failed. I wanted to spend some time debugging the PMP issues for the new bitstream but without verilator I don't have a practical way to do so

2022-06-27 00:36 UTC, alistair23 commented on boards/opentitan/README.md
> +[raw docs via git](https://github.com/lowRISC/opentitan/tree/199d45626f8a7ae2aef5d9ff73793bf9a4233711/doc/ug).
Fixed

2022-06-27 00:43 UTC, alistair23 commented
These instructions won't work for the newer commits, as the build system has swapped to Bazel. Have a look at https://github.com/tock/tock/pull/3056 instead.

You should see some signs of life in around 5 minutes on Verilaotr, so 40 minutes seems too long

2022-06-28 15:37 UTC, phil-levis commented
Alistair, have you tried running through these instructions on a clean system with the named commit?

2022-06-28 22:33 UTC, alistair23 commented
Yep!

2022-06-29 21:31 UTC, bradjc approved these changes

2022-07-04 23:31 UTC, alistair23 commented
This should be ready to go, then I can rebase https://github.com/tock/tock/pull/3056 on top of it which should help for the newwer bazel builds

2022-07-07 15:33 UTC, merged