Change Led Matrix Syscall Capsule for Microbit
tock/tock pull request #3093
Opened 2022-07-18 14:42 UTC by TeodoraMiu

### Pull Request Overview

This pull request changes the way the led matrix driver works for the Microbit. Before this PR, there were two separate led matrix syscall drivers which served, practically, the same purpose. This PR:

- modifies the led_matrix capsule to be used as a service capsule instead of a syscall one
- initializes only the LedD syscall driver for the Microbit and uses the Leds exported via the Led HIL by the Led matrix service driver

### Testing Strategy

This pull request was tested using a Microbit.

### TODO or Help Wanted

Feedback for these changes is much appreciated.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2022-07-25 04:29 UTC, alexandruradovici requested changes

2022-07-25 04:29 UTC, alexandruradovici commented on capsules/src/led_matrix.rs
Delete the comments about the syscall.

2022-07-25 04:29 UTC, alexandruradovici commented on capsules/src/led_matrix.rs
Add a usage example.

2022-07-25 07:32 UTC, TeodoraMiu commented on capsules/src/led_matrix.rs
Done

2022-07-25 07:32 UTC, TeodoraMiu commented on capsules/src/led_matrix.rs
Done

2022-07-26 06:34 UTC, alexandruradovici approved these changes

2022-07-27 03:30 UTC, alexandruradovici requested changes

2022-07-27 03:30 UTC, alexandruradovici commented on boards/components/src/led_matrix.rs
> +    const LED_BITS: usize,
```suggestion
    const LED_BYTES: usize,
```

2022-07-27 03:30 UTC, alexandruradovici commented on capsules/src/led_matrix.rs
> +        assert!(ROWS * COLS / 8 + 1 == LED_BITS);
Document this assertion, explain that this is used until const generics https://github.com/rust-lang/rust/issues/76560 will be stable.

2022-07-27 03:30 UTC, alexandruradovici commented on capsules/src/led_matrix.rs
>              panic!("LED at position ({}, {}) does not exist", col, row);
Delete panic and return an `Option<Self>` that is None if the LED is not valid.

2022-07-27 03:30 UTC, alexandruradovici commented on boards/components/src/led_matrix.rs
> +    ($Pin:ty, $($L:expr),+, $(,)?) => {{
Merge this with the `led_matrix_component_buf`, as that one computes all the constant values.

2022-07-27 03:30 UTC, alexandruradovici commented on boards/microbit_v2/src/main.rs
> +const LED_BITS: usize = ROWS * COLS / 8 + 1;
```suggestion

```

The values should be computed by the macro.

2022-07-27 17:31 UTC, bradjc approved these changes

2022-08-01 09:20 UTC, TeodoraMiu commented
I believe this is good to go.

2022-08-01 14:45 UTC, hudson-ayers reviewed
I am a bit confused by this PR. Are any of the helper functions in `capsules/src/led_matrix.rs` even used anymore? What is gained from the added indirection of instantiating the led_matrix capsule if userspace is just going to use the interface of the normal LED capsule?

I may be missing something obvious here

2022-08-03 21:31 UTC, alexandruradovici commented
This PR provides the ability of using the standard LED driver even if LEDs are actually connected in a matrix that can only display one column or line at a time. Before the PR, we had a syscall driver specifically for the matrix that was identical in API with the LED driver.

The timeline that got us to this PR is:

1. When micro:bit was added, we had a led matrix sycall driver that was handling both the matrix control and system calls (identical to the LED syscall driver). This resulted in code and API duplication, as we now had two LED syscall drivers.
2. While using the micro:bit, we came across the need to use single LEDs from the matrix from within another driver. This made us add code that exposes individual LEDs from the matrix through the LED HIL.
3. As the matrix driver exposes each LED through the LED HIL, we realized that we could convert the matrix syscall driver into a driver that only controls the actual matrix and use the LED syscall driver, while removing duplicate code and API.

2022-08-04 14:41 UTC, hudson-ayers approved these changes
Thank you for the explanation, that makes sense.

bors r+

2022-08-04 15:02 UTC, merged