cortex-m: cleanup linker constants
tock/tock pull request #3150
Opened 2022-08-18 17:56 UTC by ppannuto

### Pull Request Overview

This is the follow-on to #3147 that does the real fix here. I still think #3147 should go in for 2.1 as a quick-fix, and then this can come in after as the better fix.

This fixes the type imports from the linker script to match reality (they're const pointers). I think this was just some real legacy stuff that predated our understanding of Rust.

### Testing Strategy

Todo: will test on HW when I'm in the office next week.

### TODO or Help Wanted

^see above

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2022-08-18 20:11 UTC, hudson-ayers requested changes
I think we should also apply these changes to here: https://github.com/tock/tock/blob/915863ef09fd3b0c933484362b2fdcf44111ca22/boards/opentitan/src/main.rs#L661 and here https://github.com/tock/tock/blob/master/arch/rv32i/src/lib.rs#L23 and here https://github.com/tock/tock/blob/master/boards/components/src/process_console.rs#L73 ?

2022-10-10 15:06 UTC, hudson-ayers commented
> I think we should also apply these changes to here:
> 
> https://github.com/tock/tock/blob/915863ef09fd3b0c933484362b2fdcf44111ca22/boards/opentitan/src/main.rs#L661
> 
> and here https://github.com/tock/tock/blob/master/arch/rv32i/src/lib.rs#L23 and here https://github.com/tock/tock/blob/master/boards/components/src/process_console.rs#L73 ?

I think this comment still applies

2022-10-21 17:55 UTC, ppannuto commented
Yep, I false-started on cleaning that up and finishing this the other day; will roll this over from draft to ready when it's actually ready.

2023-10-09 15:38 UTC, bradjc commented
Can we merge this?

2023-10-09 16:06 UTC, brghena approved these changes

2023-10-10 03:58 UTC, alistair23 approved these changes

2023-11-19 22:22 UTC, hudson-ayers approved these changes
Just realized this was held up by my requested changes, sorry about that

2023-11-19 22:38 UTC, merged