Component: Move ADC components to new _static macro
tock/tock pull request #3231
Opened 2022-09-20 18:30 UTC by bradjc

### Pull Request Overview

This pull request updates the ADC components to use the _static component macro convention and static_buf!().

### Testing Strategy

travis

### TODO or Help Wanted

Need temperature PR to go through first.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2022-10-03 16:05 UTC, phil-levis submitted a review, later dismissed

2022-10-04 18:51 UTC, hudson-ayers approved these changes

2022-10-04 23:10 UTC, alistair23 approved these changes

2022-10-05 01:06 UTC, hudson-ayers requested changes
Actually, after some testing, the first commit in this PR causes the compiler to optimize out almost the entire kernel binary of any Tock board that uses the new `AdcDedicatedComponent`, so this should not be merged until we fix that.

2022-10-12 23:47 UTC, hudson-ayers commented
rebased on top of #3290

2022-10-14 05:17 UTC, hudson-ayers submitted a review, later dismissed

2022-10-14 20:53 UTC, hudson-ayers approved these changes
bors r+

2022-10-14 21:23 UTC, merged