ADC pending command functionality
tock/tock pull request #3368
Opened 2023-01-05 11:42 UTC by TeodoraMiu

### Pull Request Overview

This pull request changes the way the ADC capsule receives commands from apps. Before this PR, the ADC capsule could only handle one command at a time. This PR would allow the ADC capsule to set an incoming command as pending if the requested ADC channel is already in use, and run the pending command after the currently active command finishes.

### Testing Strategy

This pull request was tested on a Microbit, using a fake ADC driver to simulate the case in which two commands can overlap.

### TODO or Help Wanted

Feedback is greatly appreciated.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2023-01-05 14:55 UTC, alexandruradovici requested changes
Please add a comment explaining how the syscall driver works and how applications can you it, describing the exact rules that apply.

2023-01-05 14:55 UTC, alexandruradovici commented on capsules/src/adc.rs
> +            if self.current_app.is_none() {
We renamed `appid` to `processid`, you might want to update your branch or just change the name of the variable here.

2023-01-05 14:55 UTC, alexandruradovici commented on boards/components/src/adc.rs
> -        use kernel::static_init;
Please keep this line, as the macro might be used in places where `static_init` is not defined.

2023-01-05 14:55 UTC, alexandruradovici commented on capsules/src/adc.rs
> +                self.current_app.set(appid);
```suggestion
                self.current_process.set(appid);
```
Please rename `current_app` to `current_process` in all places.

2023-01-05 21:19 UTC, phil-levis approved these changes
Ah, nice. It looks like the machinery was there (`pending_command`) but it wasn't being used.

Can you explain your refactoring of `enqueue_command`?

2023-01-06 01:51 UTC, alistair23 approved these changes

2023-01-06 09:58 UTC, alexandruradovici approved these changes

2023-01-09 08:56 UTC, TeodoraMiu commented
> Can you explain your refactoring of `enqueue_command`?

The enqueue_command function has been slightly changed: if the current process is none, there is no need to enter the grant. Therefore, I only enter the grant when there is an active process and the new command must be set as pending.

2023-01-25 22:58 UTC, hudson-ayers commented
bors r+

2023-01-26 00:26 UTC, merged