kernel: process: freshen comments
tock/tock pull request #3452
Opened 2023-05-24 23:32 UTC by bradjc

### Pull Request Overview

Make formatting consistent, add missing comment docs, minor clarifications.

### Testing Strategy

n/a

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2023-06-08 21:49 UTC, ppannuto requested changes
I think we either need to have a tool automatically wrapping comments to some maintained, specified width or you need to turn off automatic, whole file rewrapping in your editor.

It's really hard to figure out what actually changed with a lot of the doc updates, and churn for different, arbitrary line wrap setting doesn't feel worth it — here, it made what looks like some intentional formatting worse in a least one case.

2023-06-08 21:49 UTC, ppannuto commented on kernel/src/process.rs
> +    /// flash_integrity_end.
this looks strictly less readable

2023-06-08 21:55 UTC, bradjc commented
> I think we either need to have a tool automatically wrapping comments to some maintained, specified width

I wouldn't argue with that!

> or you need to turn off automatic, whole file rewrapping in your editor.

I'm doing this manually. To me, the kernel crate is the most core crate to understand Tock, and it's worth having consistency in the presentation, even if that means periodic updates to the file because it is difficult to handle on each PR. I personally am willing to block PRs to the core kernel files until the comments are consistent, but I don't think that overhead is less than just doing it periodically.

> arbitrary line wrap setting

I wouldn't say it's completely arbitrary, at least not within this PR, it's 80 characters like the other comments in the file.

2023-06-16 19:22 UTC, bradjc commented
Anyone else have any thoughts? I think formatting comments is valuable. I also think that if the specific wrapping of a comment matters it should be in code block, since the formatting is not going to be preserved on the generated HTML docs anyway.

2023-06-20 19:31 UTC, lschuermann commented
> Anyone else have any thoughts? I think formatting comments is valuable.

My 2ct are: well-formatted docs are nice, but if something doesn't look too terrible we shouldn't necessarily feel the need to reformat it. So I don't think it's a big deal either way.

To give some examples: if somethings formatted to wrap at 70 chars, it seems fine to keep it that way. If inserting a missing word pushes a comment above the 80 chars limit, I don't know whether we need to re-wrap 20 other lines because of that.

I think the way we handled this previously was just fine, where people generally wouldn't re-wrap comments for minor changes, and then every once in a while or on major refactors, we'd adjust formatting.

2023-06-20 19:32 UTC, lschuermann approved these changes

2023-06-25 20:06 UTC, hudson-ayers approved these changes
I generally agree with Leon. For future PRs, I would prefer a two-commit approach where one commit includes the new text, and a separate commit just adjusts comment wrapping, to simplify reviewing

2023-06-26 13:47 UTC, bradjc commented
Easy enough to do. First commit is all of the formatting changes, second commit is text changes.

2023-06-29 18:22 UTC, lschuermann approved these changes

2023-06-29 19:22 UTC, merged