KV: set operation now overwrites existing key
tock/tock pull request #3546
Opened 2023-07-17 23:02 UTC by bradjc

### Pull Request Overview

This pull request updates the KVStore interface to enable set to overwrite an existing key, assuming the caller has permission to do so.

Before set with an existing key would fail, and the user would have to call delete then set again.

This also makes a small fix to tickv to return the length of the value buffer so we can reconstruct the leasable buffer when the value buffer is passed back.

### Testing Strategy

Using the interactive kv app.

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2023-07-19 02:04 UTC, alistair23 commented
This has a large downside though.

Currently if a user application calls set they are guaranteed that if there is a power failure nothing already written to flash will be lost. And once they get the set_complete callback they are guaranteed that the data is written to flash.

This changes that guarantee. If they call set and there is existing data, that existing data could be deleted and then a power loss will result in lost data.

I think this should be a new syscall that an application can use, so they can choose to take that risk or not

2023-07-19 02:04 UTC, alistair23 requested changes

2023-07-19 02:04 UTC, alistair23 commented on kernel/src/hil/hasher.rs
> +    fn add_data_done(&self, result: Result<(), ErrorCode>, data: LeasableBuffer<'static, u8>);
Actually I think this just needs a rebase

2023-07-19 13:59 UTC, bradjc commented
> This changes that guarantee. If they call set and there is existing data, that existing data could be deleted and then a power loss will result in lost data.

What does an application do today to prevent this? The base case is the app:

```
calls get(K) -> succeeds
calls set(K) -> failure
calls delete(K) -> success
calls set(K) -> success
```

but if the power failure happens between 3 and 4:

```
calls get(K) -> succeeds
calls set(K) -> failure
calls delete(K) -> success
!! Power failure
-- reboot
calls get(K) -> fails
```

Wouldn't the application have a missing key either way?

In the current case with a power failure, I guess the app would get a delete callback, and not the second set callback. But I'm not sure what the app does with that as it can't store which callbacks it got for after the power cycle.

Also, this is assuming the power failure happens conveniently while the app is executing. It could also happen before or after the operation in the kernel. Does the current implementation provide robust guarantees?

2023-07-19 17:07 UTC, bradjc commented
I thought about this a little more, and I think we need to decide what the interfaces we have are supposed to do and what niche they fill. We have `KVSystem` and this other interface (I'm calling it `KV` for now).

I think that if an app is looking for low-level control, then it should be using `KVSystem`. I think the benefit of having `KV` is that provides a user-friendly API. There's no guarantee that `KV` will be implemented on top of `KVSystem`, or even on top of flash. And while we can say that a `set()` when the key already exists returns an error, I'm not sure we can make any promises about resiliency to power failures in a `set()` API.

2023-07-21 14:16 UTC, bradjc commented
Another challenge this brings up is how to enforce the `StoragePermissions`. Right now I don't think we are doing it correctly (and I need to add a commit to my other PR to handle this still).

If a key exists with say writeid 1, and an app with accessid 1 but write id 7 calls set(key, val), then the value should be changed, _but the stored writeid should remain 1_.

Right now, what would happen is:

```
kv exists with writeid=1
app2 calls set(key, val) -> error
app2 calls delete(key) -> success (access id permits this)
app2 calls set(key, val) -> success (kv is now stored with writeid=7)
```

And the original app could lose access.

By internalizing that process we can prevent this from happening, and ensure the stored writeid remains 1.

However, this raises a new question, as the app can still manually do delete then set, changing the stored writeid. This seems bad. Is that what we expect to happen?

2023-07-24 05:25 UTC, alistair23 commented
> Wouldn't the application have a missing key either way?
> 
> In the current case with a power failure, I guess the app would get a delete callback, and not the second set callback. But I'm not sure what the app does with that as it can't store which callbacks it got for after the power cycle.

Yes, currently data would be lost if there was a power cycle after deleting the key. The difference though is that this is obvious to an application developer. When they write the application they know this could happen and can either take steps to mitigate it or decide that it's acceptable for their use case. Hiding this in the kernel is what I'm worried about.

> Also, this is assuming the power failure happens conveniently while the app is executing. It could also happen before or after the operation in the kernel. Does the current implementation provide robust guarantees?

We don't make any guarantees until the call back is called. So the current data could be lost, but no previous data will be

2023-07-24 05:34 UTC, alistair23 commented
> If a key exists with say writeid 1, and an app with accessid 1 but write id 7 calls set(key, val), then the value should be changed, _but the stored writeid should remain 1_.
> 
> Right now, what would happen is:
> 
> ```
> kv exists with writeid=1
> app2 calls set(key, val) -> error
> app2 calls delete(key) -> success (access id permits this)
> app2 calls set(key, val) -> success (kv is now stored with writeid=7)
> ```
> 
> And the original app could lose access.

Hmmm... I'm not convinced this is incorrect.

In a full blown file system I see that a different user could modify your data, but it's still your data so you should own it. But as you said, a different app can manually delete and re-write the data in this case, which is how a K/V works. So this to me seems like the correct behaviour.

If you are giving another application write access to your data you have to trust that it will do what you expect it to.

2023-07-24 15:24 UTC, bradjc commented
> this is obvious to an application developer

I'm not sure why this would be obvious to an application developer. I certainly didn't think of it.

> can...take steps to mitigate it

It's not clear to me what these steps are. I'm guessing the invariant the application developer wants is for the key to exist, either with the old or the new value.

Currently, there is no guarantee that any operation is atomic across power cycles. If the app calls set() or delete() a power failure could happen and the app would reboot and its possible any scenario has happened:
- The old key is still there because the power failure happened before the write/delete.
- The old key is gone because the power failure happened after the delete but before the callback.
- The new key is there because the second set happened and power failure occurred before the callback.

In any case, the app has to just retry the entire process, doesn't it? What can the developer do with a set() that fails on a key collision to better handle power failure uncertainties? I think if I can see an example of this that would help me understand, because I'm not seeing what benefit the current set provides but I am seeing the downside for the common case.



> BUT once the application gets the callback we know the data has been written and the software then guarantees that it won't be compromised or lost in the future.

This is true in either version of set().

2023-07-24 22:56 UTC, alistair23 commented
One of the [guarantees of TicKV](https://github.com/tock/tock/tree/master/libraries/tickv#system-guarantees) is that once data is written, it will not be lost, unless specifically deleted by a user.

So, as an application if you write data and receive the "data written" callback, you know that the data is stored and safe.

If you delete that data, like your example

```
calls get(K) -> succeeds
calls set(K) -> failure
calls delete(K) -> success
calls set(K) -> success
```

It is very obvious to you that the data is no longer stored, because you deleted it, There is no hidden operations going on behind your back

> Currently, there is no guarantee that any operation is atomic across power cycles. If the app calls set() or delete() a power failure could happen and the app would reboot and its possible any scenario has happened:
> 
>     * The old key is still there because the power failure happened before the write/delete.
> 
>     * The old key is gone because the power failure happened after the delete but before the callback.
> 
>     * The new key is there because the second set happened and power failure occurred before the callback.

Yes, if the callback hasn't happened you aren't guaranteed anything. All you are guaranteed is that once something is committed, it will stay committed. Some systems might perform live defrags for example, which could loose data on a power cycle.

A good example is CTAP/Webauthn Authentication. If Tock is running a CTAP application and a requester calls[ MakeCredential](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#authenticatorMakeCredential) we want to generate a credential, store it and only once it is stored return the successful attestation object.

In this case we will only return success AFTER the data has been safely stored to flash. So if a power cycle happens mid operation, we can just start again as the requester will timeout or retry. But we don't want to modify existing entries, because then we could loose data.

If we start modifying data behind the back of the application we loose that feature and instead could loose already stored data

2023-07-25 13:13 UTC, bradjc commented
I think I understand the difference, but I don't understand the significance. The normal case is the same: once set() issues a successful callback the data are there in this version and in the current version.

The difference is in a failure case: now it would be possible to call set with an existing key and end up with no key stored. I think it's worth noting that this is not a tickv interface, and we can't assume the KV interface is built on tickv. A different underlying storage engine might provide different primitives. It may or may not be built on kv_system interface.



> In this case we will only return success AFTER the data has been safely stored to flash. So if a power cycle happens mid operation, we can just start again as the requester will timeout or retry. But we don't want to modify existing entries, because then we could loose data.


> A good example is CTAP/Webauthn Authentication. If Tock is running a CTAP application and a requester calls[ MakeCredential](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#authenticatorMakeCredential) we want to generate a credential, store it and only once it is stored return the successful attestation object.
> 
> In this case we will only return success AFTER the data has been safely stored to flash. So if a power cycle happens mid operation, we can just start again as the requester will timeout or retry. But we don't want to modify existing entries, because then we could loose data.


I don't understand how this would work. There are two cases:

1. This is the first time making a credential (ie the key is not already stored). new set() works the same as old set().
2. The is not the first time making this credential (ie the key is already stored). Now there are two cases again:
    1. We could store the new credential under a new key. set() works like it does today.
    2. We want to re-use the existing key. This is I suppose the interesting case. How can we store the key without the chance of losing data? We can't call delete(), because then we lose data. But then we cannot call today's set() because it will fail every time with a collision. 
        
        There is a slight semantic difference in the app itself calling delete and arguing that if you delete your data you aren't losing them since you actively chose to delete them. But do app developers care about this semantic difference? Either way, if power failure happens at an inopportune time and the app reboots, the data are gone. In both cases, I think you have to retry the entire app credential process.

I want to bring up my earlier point, which is this seems like why we have multiple layers of HILs. Developers that want to do everything themselves can use the lower layer HIL. Developers that want a more convenient interface can use the upper layer HIL.

2023-08-02 15:28 UTC, alistair23 commented
> I think it's worth noting that this is not a tickv interface, and we can't assume the KV interface is built on tickv

Yep, I agree. It slipped through the cracks originally, but I think should specify that set can fail if the key exists and won't perform operations behind your back. That way if the backend reliably stores data the operation will support that. All we then need to do is add a `set_nofail` that will delete the key, and just explain the trade off.



> 2\. We want to re-use the existing key. This is I suppose the interesting case. How can we store the key without the chance of losing data? We can't call delete(), because then we lose data. But then we cannot call today's set() because it will fail every time with a collision.

So we can return an error. Maybe the user needs to run a maintenance operation, maybe the requester needs to use a difference nonce/ID/whatever, maybe the user just can't add that value. It allows the application to decided what to do based on a series of trade offs.

Another option is the application can migrate a key, ensuring that at all times there is at least one copy stored in a backup value. Again I think it just depends on the use case and how important the data is.



> I want to bring up my earlier point, which is this seems like why we have multiple layers of HILs. Developers that want to do everything themselves can use the lower layer HIL. Developers that want a more convenient interface can use the upper layer HIL.

Only one layer is exposed to user space though. I don't think we want to go down a path of exposing a range of different APIs to userspace. To me just adding a `set_nofail` (or a different name) seems the simplest

2023-08-02 15:33 UTC, bradjc commented
> Only one layer is exposed to user space though. I don't think we want to go down a path of exposing a range of different APIs to userspace. To me just adding a `set_nofail` (or a different name) seems the simplest

This is what the latest version does. We now have set/add/update and callers can choose which operation they want.

Longer term, we would like to implement set so that it guarantees that either the old data or the new data will be present, and not both or neither.

2023-08-02 15:37 UTC, alistair23 commented on libraries/tickv/src/async_ops.rs
> +                (ret, value_length)
You need to update the doc comments

2023-08-02 15:59 UTC, bradjc commented
This PR has moved to https://github.com/tock/tock/pull/3551. Originally they were two separate changes, but it makes less sense to reason about them separately. The commits from this PR are the first commits for that PR.

I didn't want to lose this discussion though.

2023-08-02 19:12 UTC, alistair23 commented
https://github.com/tock/tock/pull/3551 is a big change! Looking at the description though it looks good so far. Maybe we should close this and just move to https://github.com/tock/tock/pull/3551

2023-08-02 19:14 UTC, bradjc commented
Moved to https://github.com/tock/tock/pull/3551

2023-08-02 19:14 UTC, closed without merging