Enforce driver liveliness check
tock/tock pull request #3613
Opened 2023-08-13 08:33 UTC by Samir-Rashid

### Pull Request Overview

The driver liveliness check is defined in TRD104 4.3.1. I have updated all drivers in advance of Tock v3 (closes #3375). Make code comments and documentation consistent with regards to "driver existence check" terminology -- change as per #2908. "Driver check" falsely implies some sort of functionality checking.

### Testing Strategy

Unsure how to test. These are breaking changes.

### TODO or Help Wanted

There seems to be an established convention that command code 0 should return the number of things the driver is controlling. I moved those commands to the next available command code. Should these syscalls have some standardized code number?

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2023-08-14 23:01 UTC, bradjc commented
It's great that this is a comprehensive change because we do want cmd 0 to be a way to check if the driver exists. We don't want people starting from capsules that do not follow this convention so it's great to remove this broadly.

We can't change the cmd==0 for the drivers with a check in the "2.0" column here: https://github.com/tock/tock/blob/master/doc/syscalls/README.md As the comments indicate we can't change those until Tock 3.0.

For the others we can change, and I think we should.

> Should these syscalls have some standardized code number?

I think generally using "1" would make sense, but I don't think it's worth changing existing drivers to match. Just adding them as the next available number makes sense to me for existing drivers.

2023-08-14 23:02 UTC, bradjc requested changes
We can't break the stability guarantees.

2023-08-17 04:04 UTC, Samir-Rashid commented
As I reverted stable drivers, I noticed there is no PWM driver [listed](https://github.com/tock/tock/blob/master/doc/syscalls/README.md#hardware-access). It should be there as it has an allocated driver number 10 (in hex?).

2023-08-22 04:47 UTC, hudson-ayers commented
> As I reverted stable drivers, I noticed there is no PWM driver [listed](https://github.com/tock/tock/blob/master/doc/syscalls/README.md#hardware-access). It should be there as it has an allocated driver number 10 (in hex?).

Good catch, feel free to add that in this PR or another standalone one!

2023-08-22 18:40 UTC, bradjc commented on capsules/core/src/adc.rs
> +            // compliance as part of the next major release of Tock. See #3613.
Can we point to #3375 instead? That is the tracking issue that will remain open for a possible 3.0 release.

2023-08-22 18:50 UTC, bradjc commented on capsules/core/src/gpio.rs
> +            0 => CommandReturn::success(),
I think we need PRs open for libtock-c and libtock-rs to make this change.

https://github.com/tock/libtock-c/blob/master/libtock/gpio.c
https://github.com/tock/libtock-rs/blob/master/apis/gpio/src/lib.rs#L64

2023-08-22 18:50 UTC, bradjc commented on capsules/extra/src/analog_comparator.rs
> +            return CommandReturn::success();
Need pr: https://github.com/tock/libtock-c/blob/master/libtock/analog_comparator.c#L8

2023-08-22 18:50 UTC, bradjc commented on capsules/extra/src/gpio_async.rs
>          if command_number == 0 {
We don't use this in libtock-c so we are good here.

2023-08-22 18:50 UTC, bradjc commented on capsules/extra/src/read_only_state.rs
> +            1 => CommandReturn::success_u32(VERSION),
https://github.com/tock/libtock-c/blob/master/libtock/read_only_state.c#L3

2023-10-03 07:21 UTC, Samir-Rashid commented
Apology for delay. [Here](https://github.com/Samir-Rashid/tock/commit/ce1d50804fcf85a2779ec62503b50073838b24f8) is a diff of what I changed in case GitHub gets confused when I squash again. I made accompanying PRs https://github.com/tock/libtock-c/pull/349 and https://github.com/tock/libtock-rs/pull/517

2023-10-06 16:37 UTC, ppannuto approved these changes
I think this is looking pretty good. It's a lot of changes, but it's a nice consistency pass over a pretty old part of the kernel interface. It doesn't look like any stabilized interfaces are changed (though some of the documentation gets small updates in the name of consistency—which is good IMO).

2023-10-06 16:37 UTC, ppannuto commented on doc/syscalls/00007_analog_comparator.md
> +* ### Command number: `3`
Just noting for myself: this is not a change per se, but a fix of a documentation bug

2023-10-06 16:48 UTC, bradjc approved these changes

2023-10-09 16:48 UTC, merged