Make UART registers for Nrf52840 configurable
tock/tock pull request #3722
Opened 2023-10-25 05:52 UTC by Niederb

### Pull Request Overview

This PR makes the registers of the UART implementation for the Nrf52840 configurable by passing them into the constructor. This allows boards to re-configure the UART or to support additional UARTs.
Also see the related issue #3720 

### Testing Strategy

Only changes that can be tested by compilation.

### TODO or Help Wanted

No help required.

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

2023-10-25 05:57 UTC, alistair23 approved these changes

2023-10-25 08:19 UTC, lschuermann approved these changes

2023-10-27 16:18 UTC, bradjc requested changes
I don't think we want to expose `UARTE0_BASE` to boards. Instead we have a model for multiple peripherals (see the SPI driver for the nrf52).

2023-10-30 10:40 UTC, Niederb commented
@bradjc Just for clarification:
You mean having an `INSTANCES` array of `UarteRegisters` and passing an index (basically the UART number) for that array into the constructor?

2023-11-01 17:23 UTC, bradjc approved these changes
On a closer look actually this is fine. I was mixing up io.rs and main.rs and all together got myself confused.

I don't really have a preference between passing in the static ref directly or using an index (and different chips/peripherals do different things) so that is fine.

2023-11-01 17:50 UTC, merged