Common build script
tock/tock pull request #3782
Opened 2024-01-10 15:20 UTC by jwnrt

### Pull Request Overview

This pull request consolidates all board `build.rs` scripts into a common `boards/build.rs`.

Currently, all build scripts are used to print `cargo:rerun-if-changed=...` lines for the link scripts that they use. Some are missing these lines for scripts that are included in `layout.ld`.

One build script (imxrt1050-evkb) was also tracking a `hdr.s` file, but as far as I can tell this file is not used so I have removed it.

The motivation for this change is to simplify the repo and make `build.rs` scripts less error prone (e.g. fixing the ones that miss `rerun-if-changed` lines). I also hope that having only one `build.rs` script will open Tock up to moving some configuration out of `Makefile`s to Cargo such that `cargo build` works (but `make` would likely still be used).

Apologies for another PR that touches loads of files :)

### Testing Strategy

1. Run `make boards` to make sure they all compile.
2. Re-run `make` for a board to ensure it does not recompile.
3. Touch the board's `layout.ld` and run `make` to check that it _does_ recompile / relink.
4. Touch `kernel_layout.ld` and run `make` to check that included files trigger recompilation too.

### TODO or Help Wanted

If, in the future, boards need something else in their `build.rs` script, they will not be able to use this shared script. I think in that case the `track_link_script` function could be put in a tiny `build-utils` crate or similar and used by individual build scripts as a `[build-dependency]` in their custom `build.rs` scripts to avoid duplicating the code. Does that sound acceptable?

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

I only found `build.rs` references in `doc/Compilation.md` and doc/Porting.md`.

### Formatting

- [x] Ran `make prepush`.

2024-01-10 16:32 UTC, bradjc requested changes
I like that this is more principled in actually finding included linker scripts and declaring the dependency on all of them.

One reason we haven't gone to a communal build.rs is doing so adds a little bit of customization to Tock which isn't "normal" (i.e. it's different than how an arbitrary rust crate on github would look). This adds a bit of friction for new developers and for building on Tock.

That being said, I think this PR is a reasonable balance. It doesn't use symlinks or anything custom to find the build.rs file, it uses a [documented](https://doc.rust-lang.org/cargo/reference/manifest.html#the-build-field) feature of Cargo.toml. In exchange, we get a much better build.rs and less duplicated code.

I do think we need to update https://github.com/tock/tock/blob/master/doc/OutOfTree.md to discuss this change and what we recommend. Should users copy the new build.rs file? Or somehow point to it? Or just make their own? We have examples of out-of-tree boards in the tock org, specifically for the bootloader (ex: https://github.com/tock/tock-bootloader/tree/master/boards/wm1110_dev-bootloader).

2024-01-10 16:32 UTC, bradjc commented on boards/build.rs
> +
Please add a header doc comment with some of the info from the PR (what this file is and how a board should use it).

2024-01-10 16:51 UTC, jwnrt commented
I have updated `doc/OutOfTree.md` to include a link to the Tock submodule's `build.rs` file in the example it gives.

I see that [tock-bootloader](https://github.com/tock/tock-bootloader/blob/master/boards/wm1110_dev-bootloader/build.rs) does use a custom build script. I haven't mentioned what to do in that case but at least by describing the script in the documentation, out-of-tree boards will know what to reproduce in their own build scripts.

Does that sound okay to you?

2024-01-10 17:33 UTC, bradjc approved these changes

2024-01-10 23:01 UTC, alistair23 approved these changes

2024-01-12 14:19 UTC, lschuermann approved these changes
This is great.

2024-01-22 15:40 UTC, lschuermann commented
Marking last call given we talked about it last Friday.

2024-01-24 18:37 UTC, merged