doc: syscall: add K-V syscall doc
tock/tock pull request #3785
Opened 2024-01-10 19:00 UTC by bradjc

### Pull Request Overview

This pull request adds syscall documentation for the KV interface.

[Rendered](https://github.com/tock/tock/blob/syscall-kv-doc/doc/syscalls/50003_key_value.md)

### Testing Strategy

na

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2024-01-11 02:58 UTC, alistair23 requested changes

2024-01-11 02:58 UTC, alistair23 commented on doc/syscalls/50003_key_value.md
> +  Use RO allow 0 to set the key and RO allow 1 to set the value.
We don't need RO allow 1

2024-01-11 02:58 UTC, alistair23 commented on doc/syscalls/50003_key_value.md
> +  Use RO allow 0 to set the key.
hashed key?

2024-01-11 03:40 UTC, bradjc commented on doc/syscalls/50003_key_value.md
> +  Use RO allow 0 to set the key.
No it's just any key.

2024-01-11 03:40 UTC, bradjc commented on doc/syscalls/50003_key_value.md
> +  Use RO allow 0 to set the key and RO allow 1 to set the value.
The interface currently uses it.

2024-01-11 15:38 UTC, bradjc commented on doc/syscalls/50003_key_value.md
> +  Use RO allow 0 to set the key and RO allow 1 to set the value.
Oh my bad.

2024-01-11 15:48 UTC, bradjc commented on doc/syscalls/50003_key_value.md
> +  Use RO allow 0 to set the key and RO allow 1 to set the value.
Fixed.

2024-01-11 21:50 UTC, alistair23 approved these changes

2024-01-12 14:20 UTC, lschuermann approved these changes

2024-01-24 01:26 UTC, bradjc commented
This seems like an easy merge?

2024-01-24 18:54 UTC, merged