arch/cortex-m: hard_fault_handler: fix incorrect return to PSP stack
tock/tock pull request #3798
Opened 2024-01-15 18:51 UTC by lschuermann

### Pull Request Overview

This fixes a critcial bug in the ARMv7m hard-fault handler. Prior to this fix, it is possible (depending on the compiler) that the hard-fault handler may return to an application's context (the PSP stack), but *in privileged handler mode*. This effectively and trivially allows an application to execute arbitrary code at kernel privileges.

Tock's Cortex-M hard-fault handlers are split into a base handler (implemented through a `#[naked]` function that does not generate a function prologue / epilogue), and a non-naked `_continued` function which can contain arbitrary Rust code. Once the base handler has done sufficient preparations (make stack space for the subsequent handler, in case of a kernel stack overflow), the handler jumps to the `_continued` function. This function is expected to only return if the hard-fault has been caused by unprivileged user-mode code. In this case, the CONTROL register is set to switch to privileged thread mode, and the link register (LR) is set to `0xFFFFFFF9` (return to Thread mode, restoring state from the main stack pointer MSP). Finally, upon return, the naked handler is supposed to branch to this LR address:

    00020e4c <_RNvCsiXETrHxse8y_7cortexm26hard_fault_handler_arm_v7m>:
       20e4c:       f04f 0100       mov.w   r1, #0
       20e50:       f01e 0f04       tst.w   lr, #4
       [...]
       20e78:       46a5            moveq   sp, r4
       20e7a:       f000 b807       b.w     20e8c <_RNvCsiXETrHxse8y_7cortexm36hard_fault_handler_arm_v7m_continued>
       20e7e:       4770            bx      lr

However, because the `_continued` function is a non-naked function, the Rust compiler / LLVM may generate an arbitrary function epilogue. This epilogue may overwrite the LR register upon return.

```rust
unsafe extern "C" fn hard_fault_handler_arm_v7m_continued(
    faulting_stack: *mut u32,
    kernel_stack: u32,
    stack_overflow: u32,
) {
    use core::arch::asm;
    if kernel_stack != 0 {
        [...] // This branch never returns
    } else {
        asm!(
            [...]
            "movw LR, #0xFFF9",
            "movt LR, #0xFFFF",
            options(nostack),
         );
    }
}
```

The above code can, for instance, generate the following assembly:

    00020e8c <_RNvCsiXETrHxse8y_7cortexm36hard_fault_handler_arm_v7m_continued>:
       20e8c:       b5fe            push    {r1, r2, r3, r4, r5, r6, r7, lr}
       20e8e:       af06            add     r7, sp, #24
       [...]
       20ebc:       f3bf 8f6f       isb     sy
       20ec0:       f64f 7ef9       movw    lr, #65529      @ 0xfff9
       20ec4:       f6cf 7eff       movt    lr, #65535      @ 0xffff
       20ec8:       b006            add     sp, #24
       20eca:       bd80            pop     {r7, pc}
       [...]

In this case, the `pop {r7, pc}` instruction returns from the function, but to the stacked `lr` instead of the newly written return address. This stacked `lr` value is the faulting address in case of an instruction access fault by userspace. Thus, userspace can execute arbitrary code in the privileged handler mode.

This commit fixes this issue by calling the `_continued` function with a proper branch and link instruction, and unconditionally jumping to the `EXC_RETURN` code upon function return.

### Testing Strategy

This pull request was tested by running this code on an nRF52840DK while developing ARM Encapsulated Functions support, detecting the bug and verifying correct operation with instruction stepping in GDB.

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] ~Updated the relevant files in `/docs`,~ or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2024-01-15 19:01 UTC, lschuermann commented
Really I think that one of the underlying issues here is the desire to jump to non-naked functions for Rust execution quickly. This opens the door for these bugs to be introduced at any point in the future, depending on compiler versions, optimizations and other factors.

A more invasive fix for this is to move at least the `kernel_stack` branch out of the Rust function into the base handler ASM, to avoid interactions between those two ASM blocks needing to permute the Rust function epilogue. Also, it should be more obvious that the `kernel_stack != 0` branch cannot return so I would have liked to add this:

```diff
          if stack_overflow != 0 {
              // Panic to show the correct error.
              panic!("kernel stack overflow");
          } else {
              // Show the normal kernel hardfault message.
              kernel_hardfault_arm_v7m(faulting_stack);
          }

+         // Neither of the above functions are allowed to return (and both return
+         // the never-type !), so this should be optimized out. We want to keep a
+         // panic point in here, incase the above ever changes -- we rely on this
+         // function not returning in case of kernel hardfaults for system
+         // correctness.
+         unreachable!()
```

However, this produces a compiler warning that `unreachable!()` is unreachable, which is unfortunate.

2024-01-15 19:07 UTC, brghena approved these changes
I spent five minutes reading through all this assembly and I believe this makes sense.

In fact, I'm really confused that we ever relied on the previous version. This prior code from `hard_fault_handler_arm_v7m()` really feels like a red flag to me. If you branch but don't link, how would it ever have returned to here?
```
"b {}", // branch to function
"bx lr", // if continued function returns, we need to manually branch to link register
```

2024-01-15 19:12 UTC, lschuermann commented
I ported this fix to the `cortexm0` crate, which defines a different (`v6m`) hard fault handler and presumably suffered from the same issue. I haven't tested this beyond compiling though and am lacking access to a board to test it.

2024-01-15 19:13 UTC, lschuermann commented
> how would it ever have returned to here?

If userspace jumped to the right address. :upside_down_face:

2024-01-18 17:17 UTC, bradjc submitted a review, later dismissed

2024-01-18 17:17 UTC, bradjc commented
Any reason to wait on this?

2024-01-18 17:24 UTC, brghena commented
The change is a pretty big deal and it would be nice for at least someone else to look at the assembly. I didn't review the Cortex-M0 stuff yet, but hopefully Brad did and it looks okay

2024-01-18 17:33 UTC, lschuermann commented
> In fact, I'm really confused that we ever relied on the previous version. This prior code from `hard_fault_handler_arm_v7m()` really feels like a red flag to me. If you branch but don't link, how would it ever have returned to here?

@brghena As an aside to how this might have used to work (apart from my snarky comment above): I suspect that on a previous compiler version, the `lr` register was simply not stacked in the `_continue` function. This means that we actually branched to the overwritten `lr` value, but not with the `bx lr` instruction we intended -- instead with the one in the Rust-generated function epilogue. So my guess is that this code happened to work, until it didn't. I tried going back a couple compiler versions, and at least in the binaries produced on my system, this has been faulty for at least a year at this point.

2024-01-19 16:14 UTC, brghena approved these changes
Looked at the M0 changes

2024-01-19 19:07 UTC, ppannuto commented
Hmm.., I think the way this is written to me really looks like the intent was for `hard_fault_handler_arm_v7m_continued` to functionally be `noreturn`.

I feel like this is still a bit awkward/confusing as-written; really, in the app-fault case, we don't want to run any rust code.

I think this might be cleaner / easier to follow if the `    if kernel_stack != 0 {` check were pulled into the naked `hard_fault_handler_arm_v7m` function, and the all-assembly body of the else can then live in the 'assembly function' as well. Then, hard_fault_handler_arm_v7m_continued` can be marked `noreturn`, and the plain `b` makes more sense.

2024-01-19 19:10 UTC, lschuermann commented
@ppannuto I agree what you proposed is cleaner. I don't necessarily think it was intended as a noreturn by the trailing `bx lr`, which signals to me that the function was expected to return. 

Pulling in the if is a more invasive change though, which is why I proposed this patch first. Happy to refactor.

2024-01-19 19:10 UTC, ppannuto requested changes

2024-01-19 19:10 UTC, ppannuto commented on arch/cortex-m/src/lib.rs
> +        "bl {}", // branch to function
Think this should instead test the value of r2, and `bne hard_fault_handler_arm_v7m_continued` if it's appropriate to call into Rust, otherwise, keep going with the assembly to handle the the userland fault case.

(in practice, probably need to flip use of `r2` and `r3` above, and drop the second argument to `_continued`) as well)

2024-01-19 19:12 UTC, ppannuto commented
>  I don't necessarily think it was intended as a noreturn by the trailing bx lr, which signals to me that the function was expected to return.

I suspect if we dig into the history here, that `bx lr` is a lingering copy/paste error from when the assembly was pulled out of that function to allow for the calling-into-rust case. I doubt it was ever expected to return, rather that was just a duplicate of the `bx lr` present in the other case [and a confused comment, added later looks like].

2024-01-19 19:29 UTC, lschuermann commented
Okay, I accept defeat, looks like that's exactly what happened. :laughing:  And it looks like this is not the first time we stumble over what appears to be bug with the exact same symptoms. For future reference, here's where that change was introduced: #2350

Assembly is hard. :disappointed:

2024-01-19 20:11 UTC, lschuermann commented
@ppannuto I implemented the requested change, let me know if this looks okay to you. Not in proximity to a board right now, so this is untested still. I renamed the `_continue` handler into `_kernel`, and integrated what used to be called `kernel_hardfault_arm_v7m`. This is just another function that we need to maintain and guard behind feature flags, and also the name is confusing -- the stack overflow case is also part of the kernel hard fault handler.

2024-01-19 20:14 UTC, lschuermann commented on arch/cortex-m/src/lib.rs
> +        "bl {}", // branch to function
Makes sense. Ended up flipping `r1` and `r2` instead, but otherwise should be exactly what you proposed.

2024-01-22 14:55 UTC, lschuermann commented on arch/cortex-m0/src/lib.rs
> +/// executes on a clean stack. Is that the case right now?
I don't see how the Cortex-M0 hard fault handler makes enough stack space to handle a fault in a stack-overflow case. Can someone enlighten me how this works, or whether this is indeed missing right now?

2024-01-22 14:55 UTC, lschuermann commented
Tested the v7m code and ported changes to the v6m implementation (though that is still untested).

2024-01-26 18:48 UTC, ppannuto approved these changes
Only thing would be to update the v6m TODO a bit if you were of a mind, otherwise this is good to go from me

2024-01-26 18:48 UTC, ppannuto commented on arch/cortex-m/src/lib.rs
> +        "ldreq  r4, ={estack} /* load _estack into r4 */",
I assume this is correct as you've tested, but why is this not `={_estack}` – some weird magic around leading underscores in inline asm? (add to comment if so?)

2024-01-26 18:48 UTC, ppannuto commented on arch/cortex-m0/src/lib.rs
> +/// executes on a clean stack. Is that the case right now?
IIRC, The `panic!` macro resets the stack [same trick is used in v7m, go straight to panic on the stack overflow case].

On quick glance, the relies on the `hardfault_stacked_regsiters` not being put on the local stack — that... may or may not actually work [in the v7m case, it's a static string passed to panic, so presumably it's just loading a pointed and jumping].

Maybe update the TODO here to explain the assumption, but I don't think this needs to be fixed with this PR.

2024-01-26 18:48 UTC, ppannuto commented on arch/cortex-m/src/lib.rs
> +        "ldreq  r4, ={estack} /* load _estack into r4 */",
Ah! Nevermind, I see `estack = sym _estack,` at the close of this block now

2024-01-27 19:53 UTC, lschuermann commented on arch/cortex-m0/src/lib.rs
> +/// executes on a clean stack. Is that the case right now?
> IIRC, The `panic!` macro resets the stack [same trick is used in v7m, go straight to panic on the stack overflow case].

From a brief look at the generated assembly I can neither confirm or deny this. I only brought this up given that on ARMv7m we actually have dedicated assembly to reset the stack before calling into `panic!` (or I'm reading things very wrong):

https://github.com/tock/tock/blob/0466e1ef56822c300c3fe81e706443fd1baee7f3/arch/cortex-m/src/lib.rs#L727-L732

I was missing that same assembly on v6m.

> On quick glance, this relies on the `hardfault_stacked_regsiters` not being put on the local stack — that... may or may not actually work [in the v7m case, it's a static string passed to panic, so presumably it's just loading a pointer and jumping].

Right, that seems tricky. If `panic!` were to reset the stack, we could be lucky that this debug information is sufficiently far down the stack that it doesn't collide with the panic itself. That seems ... brittle.

> Maybe update the TODO here to explain the assumption, but I don't think this needs to be fixed with this PR.

Right. In summary I still don't feel like I have a good grasp of what's going on, but I agree that this is a separate issue.

2024-01-29 18:38 UTC, bradjc commented
Should we split the m0 changes to a separate PR?

2024-01-29 20:52 UTC, lschuermann commented
@bradjc Done: #3826

2024-01-30 02:33 UTC, bradjc approved these changes

2024-01-30 02:59 UTC, merged