Added support for 16 bit bus for I2CMasterBus
tock/tock pull request #3812
Opened 2024-01-23 11:39 UTC by Cristian243342

### Pull Request Overview

This pull request adds support for 16 bit bus for I2CMasterBus.

### Testing Strategy

This pull request is untested.

### TODO or Help Wanted

This pull request still needs testing.

### Documentation Updated

- [ ] No updates are required.

### Formatting

- [ ] Ran `make prepush`.

2024-01-23 11:41 UTC, alexandruradovici requested changes

2024-01-23 11:41 UTC, alexandruradovici commented on capsules/extra/src/bus.rs
> +            BusWidth::Bits16LE => self
Can we add all the variants here? The code should be straight forward.

2024-01-23 15:45 UTC, alexandruradovici requested changes

2024-01-23 15:45 UTC, alexandruradovici commented on capsules/extra/src/bus.rs
> +                    buffer[0] = 0x00;
```suggestion
                    buffer[0] = addr & 0xff;
```

2024-01-23 15:45 UTC, alexandruradovici commented on capsules/extra/src/bus.rs
> +                    buffer[1] = addr as u8;
```suggestion
                    buffer[1] = (addr >> 8) as u8;
```

2024-01-24 00:26 UTC, alistair23 commented
Why add this if it's untested? If it is not being used we don't need to support it

2024-02-27 03:49 UTC, lschuermann commented
> Why add this if it's untested? If it is not being used we don't need to support it

This is used and @alexandruradovici explicitly asked for it to be split out in #3811.

@Cristian243342 Do you have any updates on this?

2024-03-04 16:46 UTC, lschuermann commented
@alexandruradovici, do you know how to best proceed here?

2024-03-04 17:20 UTC, alexandruradovici commented
This is not yet done, I'll talk to my student and get back on this.

2024-06-27 16:03 UTC, lschuermann commented
@Cristian243342 @alexandruradovici  friendly ping on this.

2024-07-05 17:14 UTC, lschuermann commented
Closing due to staleness, feel free to re-open if there's progress.

2024-07-05 17:14 UTC, closed without merging