kernel: utilities: add crc32b implementation
tock/tock pull request #3825
Opened 2024-01-29 17:02 UTC by bradjc

### Pull Request Overview

This is helpful for, for one example, computing ShortIDs from process names.

### Testing Strategy

Comparing to online calculator.

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2024-01-29 18:13 UTC, lschuermann requested changes

2024-01-29 18:13 UTC, lschuermann commented on kernel/src/utilities/helpers.rs
> +pub fn crc32b_str(s: &'static str) -> u32 {
Might be nicer to have this accept a byte slice instead. This way we can use [`core:;str::as_bytes`](https://doc.rust-lang.org/stable/core/primitive.str.html#method.as_bytes) to calculate a CRC over a string, but also support other non-unicode byte sequences. Shouldn't need a lot of changes, just iterating over the bytes and removing the cast.

2024-01-30 04:53 UTC, alistair23 commented
Why not use the existing [CRC implementation](https://github.com/tock/tock/blob/master/libraries/tickv/src/crc32.rs)?

2024-01-30 05:06 UTC, bradjc commented
> Why not use the existing [CRC implementation](https://github.com/tock/tock/blob/master/libraries/tickv/src/crc32.rs)?

I think adding a dependency of tickv for this use case is pretty heavyweight. Also the kernel won't have tickv as a dependency and I need to use this in the kernel. I don't actually need CRC, I just need something of `fn(str) -> u32` that I can get merged into Tock.

2024-01-30 09:32 UTC, alistair23 commented
You could copy the same implementation though. Keep all our CRCs the same

2024-01-30 14:50 UTC, lschuermann approved these changes

2024-01-30 15:05 UTC, bradjc commented
> You could copy the same implementation though. Keep all our CRCs the same

I need something so I can do something like:

```rust
ShortID::Fixed(NonZeroU32::new(kernel::utilities::helpers::crc("circle")).unwrap())
```

Any extra machinery would just complicate that code for I don't think much benefit. 

Use case: https://github.com/tock/tock/pull/3817/files#diff-98d9b86eaf1d01d892fb1c96c448e2799cf55fa442b5ff12aa4b5d85c3d16de5R506

2024-01-31 01:24 UTC, alistair23 commented
I don't follow. You said in the PR description that this is helpful for computing shortIDs. Why do we need to use CRC-32B? Could we use CRC-32 to try to keep all of our CRCs the same?

Maybe it's worth saying why we need this exact implementation in the PR description? It's not really clear

2024-02-01 16:08 UTC, bradjc commented
Version that matches tickv in #3829

2024-02-01 16:33 UTC, bradjc commented
I don't think anyone wants to add crc32b. But the PR description is still helpful.

2024-02-01 16:33 UTC, closed without merging