boards: stm32: use std openocd config
tock/tock pull request #3926
Opened 2024-03-21 02:16 UTC by bradjc

### Pull Request Overview
Use the standard openocd config for STM boards. I've run into issues with openocd and the stm32f429zi board. It's possible this is an improvement.

I didn't include the changes to the board that I do have in this PR.

### Testing Strategy

Nothing, unfortunately. I don't have these boards. But I'm worried about bitrot with these boards.

### TODO or Help Wanted

Thoughts?

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2024-03-21 12:38 UTC, alevy approved these changes
I strongly support this. It's very likely that openocd didn't have built in support for these boards originally, but does now. If this breaks something, we can always bring this back.

2024-03-21 12:42 UTC, alevy requested changes
License headers

2024-03-21 12:42 UTC, alevy commented on boards/stm32f3discovery/Makefile
>  # Copyright Tock Contributors 2022.
```suggestion
# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.
```

2024-03-21 12:42 UTC, alevy commented on boards/stm32f412gdiscovery/Makefile
>  include ../Makefile.common
```suggestion
# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2024.

include ../Makefile.common
```

2024-03-21 12:42 UTC, alevy commented on boards/nucleo_f446re/Makefile
>  # Makefile for building the tock kernel for the NUCLEO-446RE platform
```suggestion
# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2024.

# Makefile for building the tock kernel for the NUCLEO-446RE platform
```

2024-03-21 12:42 UTC, alevy commented on boards/nucleo_f429zi/Makefile
>  include ../Makefile.common
```suggestion
# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2024.

include ../Makefile.common
```

2024-03-21 12:50 UTC, bradjc commented
I don't understand what's happening with the license headers.

2024-03-21 12:53 UTC, alevy commented
> I don't understand what's happening with the license headers.

There were some strange diffs going on, and ultimately I don't think the license headers were the problem (but rather an incorrectly removed Makefile variable). But the license headers don't hurt...

2024-03-21 12:54 UTC, alevy commented
Oh, I see... I was wrong. Will fix

2024-03-22 03:27 UTC, alevy approved these changes

2024-03-22 04:03 UTC, merged