Network working group notes, March 18 2024
tock/tock pull request #3936
Opened 2024-03-23 17:32 UTC by brghena

### Pull Request Overview

This pull request adds notes from the Network working group call on March 18th, 2024.

[Rendered](https://github.com/tock/tock/blob/93056bc7988fb365cb4530f5545b8ccd001a6f8f/doc/wg/network/notes/network-notes-2024-03-18.md)

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [N/A] Ran `make prepush`.

2024-03-25 16:10 UTC, tyler-potyondy submitted a review, later dismissed

2024-03-27 06:44 UTC, alexandruradovici requested changes

2024-03-27 06:44 UTC, alexandruradovici commented on doc/wg/network/notes/network-notes-2024-03-18.md
> +- Alex: Leon and Amalie working on buffer management. Writing and re-writing code. Constant expressions would be really really helpful here. Overall, we're still figuring out how to best use the buff
```suggestion
- Alex: Leon and Amalia working on buffer management. Writing and re-writing code. Constant expressions would be really really helpful here. Overall, we're still figuring out how to best use the buffer management system, and also how to design it. It is progressing!
```

2024-03-28 16:26 UTC, brghena commented on doc/wg/network/notes/network-notes-2024-03-18.md
> +- Alex: Leon and Amalie working on buffer management. Writing and re-writing code. Constant expressions would be really really helpful here. Overall, we're still figuring out how to best use the buff
Thank you!!

2024-04-01 14:56 UTC, alexandruradovici approved these changes

2024-04-01 15:06 UTC, merged