Network working group call notes: April 15, 2024
tock/tock pull request #3963
Opened 2024-04-15 19:23 UTC by brghena

### Pull Request Overview

This pull request adds notes from the Network working group call on April 15th, 2024.

### Testing Strategy

Documentation

### TODO or Help Wanted

Good to go

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [N/A] Ran `make prepush`.

2024-04-15 20:42 UTC, alexandruradovici requested changes

2024-04-15 20:42 UTC, alexandruradovici commented on doc/wg/network/notes/network-notes-2024-04-15.md
> +* Alex: Well, just for the buffer
```suggestion
* Alex: Well, just for the buffer it might not be worth, we can aleays use a struct with variables.
```

2024-04-15 20:42 UTC, alexandruradovici commented on doc/wg/network/notes/network-notes-2024-04-15.md
> +* Alex: It's going to be pretty ugly to instantiate. I hope there are some type aliases or something to clean that up. The HIL takes a dynamic trait
```suggestion
* Alex: It's going to be pretty ugly to instantiate. I hope there are some type aliases or something to clean that up.
```

2024-04-15 20:42 UTC, alexandruradovici commented on doc/wg/network/notes/network-notes-2024-04-15.md
> +* Alex: The constants won't be in the type on the upcall path anyways. On the downcall, it's got a UartData, but going up because it's a dynamic trait object it requires the headroom of all the layer
```suggestion
* Alex: The constants won't be in the type on the upcall path anyways.
```

2024-04-15 20:46 UTC, brghena commented on doc/wg/network/notes/network-notes-2024-04-15.md
> +* Alex: Well, just for the buffer
```suggestion
* Alex: Well, just for the buffer it might not be worth, we can always use a struct with variables.
```

2024-04-15 20:48 UTC, brghena commented
Thanks @alexandruradovici!

2024-04-16 00:55 UTC, tyler-potyondy approved these changes

2024-04-22 23:45 UTC, jrvanwhy commented
@alexandruradovici You still have requested changes, which block merging this PR.

2024-04-23 05:16 UTC, alexandruradovici approved these changes

2024-04-23 05:26 UTC, merged