kernel/collections/queue: rename `remove_first` to `remove_first_matching`
tock/tock pull request #4033
Opened 2024-06-17 15:04 UTC by lschuermann

### Pull Request Overview

`Queue`'s `dequeue_specific` was renamed to `remove_first` in ab293c54c36a ("Rename dequeue_specific to remove_first").

While I don't disagree with the fact that `dequeue_specific` is an oxymoron and a bad name, arguably `remove_first` carries its own baggage. We're talking about collections where "first" has meaning, often used interchangably with "head". Looking over the code in #3577 I was quite surprised with the complexity of this method's implementation in `RingBuffer`, for what I thought would just be a `dequeue` operation---removing the _first_ / _head_ element.

This is an effort to clear up that confusion. This is not a hill worth dying on for me, so if anyone has strong feelings otherwise, feel free to close this.

### Testing Strategy

N/A

### TODO or Help Wanted

N/A

### Documentation Updated

- [x] ~Updated the relevant files in `/docs`,~ or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2024-06-17 15:47 UTC, bradjc requested changes
Wait `dequeue_specific()` changed name? Why does "to dequeue" have to mean the front of the queue?

I think the fix is to go back to `dequeue_specific()`.

>`remove_first` is a general operation for list-like structures and better follows conventions around naming such operations.

But this isn't a list-like structure, it is a queue.

2024-06-17 15:48 UTC, bradjc commented
Also I agree with Leon that `remove_first()` is a synonym for `dequeue()`.

2024-06-17 16:01 UTC, alevy approved these changes

2024-06-17 16:11 UTC, alevy commented
I think remove_first where the argument is a lambda that takes an element and returns a bool, pretty clearly matches the implementation, which removes the first element that matches the predicate.

But I don't care very much.

2024-06-18 15:28 UTC, alevy commented
`remove_first_matching()`

Again, I'm not dying on this hill, but `dequeue` means to remove the head of a queue.

2024-06-18 20:34 UTC, ppannuto approved these changes
`remove_first_matching` feels like a winner to me.

2024-06-19 13:16 UTC, bradjc commented
Why do we have both verbs? Remove and Dequeue?

2024-06-19 18:05 UTC, alevy commented
> Why do we have both verbs? Remove and Dequeue?

Because they mean different things.

To refer to your original comments:

> Why does "to dequeue" have to mean the front of the queue?

Because that is literally the definition of a queue (<https://en.wikipedia.org/wiki/Queue_(abstract_data_type)>)

> But this isn't a list-like structure, it is a queue.

Exactly. This method is entirely breaking the abstraction that this thing is a queue (a queue can _only_ have the head removed), and exposing the fact that it is actually a list-like structure, than has an order of elements that can be removed otherwise.

Arguably, if we were interested in having more formalism here, we might have this structure and a number of traits:

```rust
trait Queue<T> {
    fn enqueue(&self, item: T);
    fn dequeue(&self) -> Option<T>;
}

trait ListLike<T> {
    fn remove_first_matching(...) -> Option<T>;
    fn remove_at(&self, i: usize) -> Option<T>;
    fn insert(&self, i: usize, item: T);
    ...
}
```

And this structure implements all of them.

But we probably don't need to have a bunch of different traits for just one data structure, so we can just put those methods in the impl directly, and name them based on the _kind_ of interface they relate to.

2024-06-19 19:04 UTC, bradjc approved these changes

2024-06-19 21:38 UTC, merged