tickv: Remove the offset from read_region()
tock/tock pull request #4069
Opened 2024-07-08 05:31 UTC by alistair23

### Pull Request Overview

read_region() originally had a `offset` argument. The idea was to avoid
reading an entire flash region and only read part of the region, by
offsetting into the region.

This was never actually supported, the idea was to be able to support it
without API breakages, but in practice I don't think that will be
possible as we will need some API changes no matter what.

As offset is never used let's just remove it. This will simplify things
a little bit and it's easy to re-add in the future if we want to support
partial page reads.

This also fixes https://github.com/tock/tock/issues/4066

### Testing Strategy

CI

### TODO or Help Wanted

N/A

### Documentation Updated

- [X] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [X] Ran `make prepush`.

2024-07-08 13:44 UTC, lschuermann submitted a review, later dismissed

2024-07-08 16:19 UTC, bradjc reviewed
Looks good other than the crc32 change.

2024-07-08 16:19 UTC, bradjc commented on libraries/tickv/src/crc32.rs
> +
?

2024-07-08 22:50 UTC, alistair23 commented on libraries/tickv/src/crc32.rs
> +
It's a clippy lint

2024-07-08 23:07 UTC, ppannuto submitted a review, later dismissed
Weird that clippy didn't bug about this till now, but it's in its own commit which looks fine 🤷🏼

2024-07-10 18:42 UTC, bradjc commented
That isn't a clippy lint we use though.

2024-07-10 22:52 UTC, alistair23 commented
If you run `cargo clippy` in the directory it warns about it. It's adding a single `Default` as [recommended](https://rust-lang.github.io/rust-clippy/v0.0.212/#new_without_default) by the Rust ecosystem. Why is this controversial?

2024-07-11 00:52 UTC, bradjc commented
I would like to fix that (#4082).

As a PR reviewer it is a lot harder when there are unrelated changes, as I expect to review tickv read code but also have to ask why not just the `Default` derive? Also PRs that have unrelated changes lead to confusing history.

2024-07-12 15:41 UTC, lschuermann commented
Marking last-call. I think regardless of the outcome of the Clippy discussion, it's probably fine to have Default be implemented for Crc32, so the changes themselves here seem uncontroversial.

2024-07-15 13:05 UTC, bradjc requested changes
Why not #derive default?

2024-07-15 23:01 UTC, alistair23 commented
> Why not #derive default?

Clippy recommended this implementation, so I went with that. I have swapped it to `#[derive(Default)]`

2024-07-16 00:15 UTC, lschuermann approved these changes

2024-07-17 03:05 UTC, alevy commented
@bradjc I think your comment is resolved?

2024-07-17 03:06 UTC, alevy approved these changes

2024-07-17 03:07 UTC, bradjc approved these changes

2024-07-17 04:28 UTC, merged