Servomotor driver
tock/tock pull request #4126
Opened 2024-08-02 09:15 UTC by inesmaria08

### Pull Request Overview

This pull request adds a SG90 capsule. 

The files added for this capsules are:
 - `capsules/extra/src/servo.rs`
 - `capsules/extra/src/sg90.rs`
 - `kernel/src/hil/servo.rs`

### Testing Strategy

This pull request was tested on a raspberry pi pico (using a Pico Explorer Base and a SG90 servo motor).

### TODO or Help Wanted

This pull request still needs feedback.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2024-08-02 14:37 UTC, bradjc commented on kernel/src/hil/servo.rs
It would probably be good to have a function that returns the maximum angle of the servo in degrees (may not be 180 for all servos). It might also help to have a read function that returns the current angle, as well as a callback for when the servo is done moving.

2024-08-02 14:37 UTC, bradjc commented on kernel/src/hil/servo.rs
> +    fn servo(&self, angle: usize) -> Result<(), ErrorCode>;
Maybe `set_angle()`?

2024-08-02 15:15 UTC, alexandruradovici requested changes

2024-08-02 15:15 UTC, alexandruradovici commented on kernel/src/hil/servo.rs
> +    /// "&self" is used so the function can modify the servomotor.
`&self` does not have to be documented.
```suggestion
```

2024-08-02 15:15 UTC, alexandruradovici commented on kernel/src/hil/servo.rs
> +    /// "angle" is the parameter that receives the angle
I suggest using the markdown lists as described here https://stackoverflow.com/questions/30009650/how-to-document-rust-function-arguments to document parameters.

2024-08-06 10:06 UTC, inesmaria08 commented on kernel/src/hil/servo.rs
The servo I'm working with cannot return its angle directly. To obtain the angle, we have two options: modify the PWM HIL to include a ⁠ current_duty_cycle ⁠ function or store and return the last angle command we sent. The issue with recalculating the angle from the duty cycle and pulse width is that the formula provides only an approximation.

Additionally, the servo changes its angle almost instantly. Should we treat this operation as asynchronous, providing an immediate callback assuming the angle has changed, or should we consider it synchronous and leave it as it is?

2024-08-06 17:57 UTC, bradjc commented on kernel/src/hil/servo.rs
I think it's fine if the driver just stores the current angle.

As for sync/async, good question. I'll try to see what others think.

2024-08-12 12:19 UTC, alexandruradovici requested changes

2024-08-12 12:19 UTC, alexandruradovici commented on capsules/extra/src/servo.rs
> +    /// - `1`: Changing the angle immediatelly. `data1` is used for the angle (0-180).
```suggestion
    /// - `1`: Changing the angle immediatelly. `data1` is used for the angle (0-360).
```

2024-08-16 15:27 UTC, bradjc commented on kernel/src/hil/servo.rs
I was thinking along the lines of what happens when the app starts executing, how does it know what setting the servo is in?

2024-08-16 18:37 UTC, inesmaria08 commented on kernel/src/hil/servo.rs
The SG90 servo I'm working with unfortunately lacks feedback on its current angle. The only way to determine the angle is either by storing the last command sent through the API (which only works if an angle command has been issued) or by calculating it based on the pulse width, which would require modifying the PWM HIL to include a `get_current_duty_cycle` function. Additionally, low-cost servomotors can have their angle manually adjusted when they are not receiving a signal (essentially when the servo is off), but there's no way to detect or report this change. We could also consider returning a "not applicable" response for servomotors that don't provide angle feedback, while keeping the function available for those that do offer angle reporting.

2024-08-16 20:53 UTC, bradjc commented on kernel/src/hil/servo.rs
It's entirely possible that it is a bad idea to have the notion that the HIL user can query the current angle (and we shouldn't have that API). But what I do want to have explicitly considered in the HIL is what the programming model is for a servo, in the context of Tock. For example, imagine an app that uses the servo is rebooted. Should the app execute as though the entire system is just starting? Or should it assume the hardware is in some state and consider that when controlling the servo? What if the servo is multiplexed in some way?

I think it is fine if we model this as a write-only device. But I think that should be done intentionally.

2024-08-17 19:22 UTC, inesmaria08 commented on kernel/src/hil/servo.rs
I see three possible approaches:

1.⁠ ⁠We can keep the HIL as write-only.

2.⁠ ⁠If we want to keep the ⁠ `get_angle` ⁠ functionality, we could introduce a new trait, like ⁠ `FeedbackServo` ⁠, which provides access to the ⁠ `get_angle` ⁠ method.
```rust

trait FeedbackServo: Servo{ ⁠
    fn get_angle(…) ⁠ ⁠
} ⁠
```

⁠3. Another option is to let the user of the HIL decide. For servos without feedback, the function would return ⁠ `Err(ErrorCode::NOSUPPORT)` ⁠, allowing the user to either treat the servo as write-only or use the result from the ⁠ `get_angle` ⁠ function when available.

2024-08-21 04:16 UTC, alevy commented on kernel/src/hil/servo.rs
A specific instance of the third option is to basically leave this to the system call driver (that is in this PR), or other virtualization layers (that are not) to keep track of, basically in memory.

2024-08-21 15:11 UTC, bradjc commented on kernel/src/hil/servo.rs
Having the API in the HIL and then making it clear that servos which don't expose that functionality in hardware in some capacity should return a specific error makes sense to me.

That does just punt the issue, however, and the same question exists for the syscall layer. Is there a guarantee on angle at initial boot so that software can track it reliably?

2024-08-21 15:49 UTC, inesmaria08 commented on kernel/src/hil/servo.rs
> That does just punt the issue, however, and the same question exists for the syscall layer. Is there a guarantee on angle at initial boot so that software can track it reliably?

No, for servos that cannot report their angle, the software needs to initialize the angle each time. The software determines whether initialization is needed based on the response returned by the function.

2024-09-11 11:48 UTC, alexandruradovici commented on kernel/src/hil/servo.rs
I suggest 2 or 3, @bradjc @alevy any preference here?

2024-09-17 15:32 UTC, alexandruradovici requested changes

2024-09-17 15:32 UTC, alexandruradovici commented on kernel/src/hil/servo.rs
> +    /// - `OFF`:  The servo was not set to an angle.
Please document that this should return `NOSUPPORT` if the servo is not able to report the angle.

2024-09-17 15:32 UTC, alexandruradovici commented on kernel/src/hil/servo.rs
As there are no comments, I suggest we go forward with 3 as this is already implmemented.

2024-09-20 14:37 UTC, alexandruradovici requested changes

2024-09-20 14:37 UTC, alexandruradovici commented on capsules/extra/src/servo.rs
> +        }
I suggest not resetting the motor angle, as there might be a servos that can keep their angle during reset and report it back.

2024-09-23 18:40 UTC, alexandruradovici approved these changes

2024-09-25 07:22 UTC, alexandruradovici commented
@alevy @bradjc do we have any other comments here or should this be good to go?

2024-09-25 07:27 UTC, alexandruradovici requested changes

2024-09-25 07:27 UTC, alexandruradovici commented on capsules/extra/src/servo.rs
> +            0 => CommandReturn::success(),
We need another command number that reports the number of servo motors available. I would use command 1 for this, 2 for `set_angle` and 3 for `get_angle`.

2024-10-11 15:56 UTC, alevy approved these changes

2024-10-13 14:02 UTC, lschuermann approved these changes

2024-10-13 14:19 UTC, merged