Core working group call notes: November 1st, 2024
tock/tock pull request #4221
Opened 2024-11-04 18:39 UTC by charles37

### Pull Request Overview

This pull request adds/changes/fixes...

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs...

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [N/A] Ran `make prepush`.

2024-11-04 19:06 UTC, ppannuto requested changes

2024-11-04 19:06 UTC, ppannuto commented on doc/wg/core/notes/core-notes-2024-11-01.md
> +- Brad working on Non-Vausal story driver upgrade
```suggestion
- Brad working on nonvolatile storage driver upgrade
```

2024-11-04 19:06 UTC, ppannuto commented on doc/wg/core/notes/core-notes-2024-11-01.md
> +- Switch to new streaming offer
```suggestion
- Switch to new streaming slices discussed earlier
```

2024-11-04 19:06 UTC, ppannuto commented on doc/wg/core/notes/core-notes-2024-11-01.md
> +
```suggestion

 - https://github.com/tock/libtock-c/pull/470
```

2024-11-04 19:06 UTC, ppannuto commented on doc/wg/core/notes/core-notes-2024-11-01.md
> +- Two parallel efforts for x86 external clemency:
Should there be a new section here?

2024-11-04 20:28 UTC, lschuermann commented on doc/wg/core/notes/core-notes-2024-11-01.md
> +- Leon Schuremann
```suggestion
- Leon Schuermann
```

It's a tough one. :smile:

2024-11-06 20:12 UTC, alevy commented on doc/wg/core/notes/core-notes-2024-11-01.md
> +- Two parallel efforts for x86 external clemency:
```suggestion
### x86 port progress

- Two parallel efforts for x86 external clemency:
```

2024-11-06 20:12 UTC, alevy approved these changes

2024-11-06 21:37 UTC, ppannuto approved these changes

2024-11-06 21:48 UTC, merged