Update `treadmill-ci` Workflow to Dynamically Select Hardware CI Tests
tock/tock pull request #4252
Opened 2024-11-25 19:45 UTC by charles37

### Pull Request Overview

- Introduce an `analyze-changes` job to the `treadmill-ci` GitHub Actions workflow.
- This job checks out both the `tock/tock` and `tock/tock-hardware-ci` repositories.
- It runs the `select-tests.py` script from `tock-hardware-ci` to select relevant hardware CI tests.
- Currently, the script selects all available tests but sets up infrastructure for future enhancements to select tests based on changes in `tock/tock`.
- Update the `treadmill-ci` job to depend on `analyze-changes` and pass the selected tests via the `tests-json` parameter.

### TODO

- [tock-hardware-ci PR #2](https://github.com/tock/tock-hardware-ci/pull/2) must be merged before this PR

### Formatting

- [N/A] Ran `make prepush`.

2024-11-25 21:01 UTC, bradjc requested changes
I think this does really require a documentation change. Right now our CI documentation is: https://github.com/tock/tock/blob/master/doc/CI_Hardware.md

Even if it is very short, something that says "We use treadmill. The operation is in the tock-hardware-ci repo. In Tock we use a github action to 1. select which tests to run and 2. invoke treadmill." would be helpful

2024-12-06 17:31 UTC, bradjc approved these changes

2024-12-11 18:44 UTC, lschuermann submitted a review, later dismissed
Looks good to me.

As discussed on last Friday's core call, merging this in tandem with tock/tock-hardware-ci#2.

2024-12-11 19:12 UTC, lschuermann approved these changes
Re-approving. This includes a minor change to no longer interpolate the `tock-hardware-ci` revision from an environment variable -- apparently, GitHub doesn't like that, but it only shows an error when trying to run this workflow.

2024-12-11 20:01 UTC, lschuermann approved these changes

2024-12-11 20:22 UTC, merged